-- Expenses quotation order fields (destructive: back up data before applying on live DB).
-- Canonical definition: db/01_schema.sql → expenses

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `expenses`;

CREATE TABLE `expenses` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int NOT NULL,
  `gl_account_id` int NOT NULL,
  `cost_center_id` int NOT NULL,
  `date` date NOT NULL,
  `invoice_date` date DEFAULT NULL,
  `posting_date` date NOT NULL,
  `payment_date` date DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `purchase_order` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `purchase_order_accepted` tinyint(1) NOT NULL DEFAULT '1',
  `quotation_order` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `quotation_order_accepted` tinyint(1) NOT NULL DEFAULT '1',
  `net_amount` decimal(12,2) DEFAULT NULL,
  `vat_amount` decimal(12,2) DEFAULT NULL,
  `total_discount` decimal(12,2) DEFAULT '0.00',
  `tax_rate_id` int DEFAULT NULL,
  `tax_rate_snapshot` decimal(5,2) DEFAULT NULL,
  `payment_mode_id` int DEFAULT NULL,
  `paid_status_id` int NOT NULL,
  `bill_id` int DEFAULT NULL,
  `invoice_id` int DEFAULT NULL,
  `supplier_id` int DEFAULT NULL,
  `currency_code` char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'EUR',
  `exchange_rate` decimal(12,6) NOT NULL DEFAULT '1.000000',
  `amount` decimal(12,2) NOT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `invoice_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `expense_recurrence_id` int DEFAULT NULL,
  `is_recursive` tinyint(1) NOT NULL DEFAULT '0',
  `next_run_date` date DEFAULT NULL,
  `recurrence_end_date` date DEFAULT NULL,
  `recurrence_source_expense_id` int DEFAULT NULL,
  `active` tinyint(1) DEFAULT '1',
  `deleted_by` int DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_expenses_company_scope` (`company_id`,`gl_account_id`,`posting_date`,`invoice_number`),
  KEY `company_id` (`company_id`),
  KEY `cost_center_id` (`cost_center_id`),
  KEY `gl_account_id` (`gl_account_id`),
  KEY `tax_rate_id` (`tax_rate_id`),
  KEY `payment_mode_id` (`payment_mode_id`),
  KEY `paid_status_id` (`paid_status_id`),
  KEY `bill_id` (`bill_id`),
  KEY `invoice_id` (`invoice_id`),
  KEY `supplier_id` (`supplier_id`),
  KEY `expense_recurrence_id` (`expense_recurrence_id`),
  KEY `recurrence_source_expense_id` (`recurrence_source_expense_id`),
  CONSTRAINT `expenses_ibfk_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `expenses_ibfk_cost_center` FOREIGN KEY (`cost_center_id`) REFERENCES `cost_centers` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `expenses_ibfk_gl_account` FOREIGN KEY (`gl_account_id`) REFERENCES `gl_accounts` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `expenses_ibfk_tax_rate` FOREIGN KEY (`tax_rate_id`) REFERENCES `tax_rates` (`id`) ON DELETE SET NULL,
  CONSTRAINT `expenses_ibfk_payment_mode` FOREIGN KEY (`payment_mode_id`) REFERENCES `payment_modes` (`id`) ON DELETE SET NULL,
  CONSTRAINT `expenses_ibfk_paid_status` FOREIGN KEY (`paid_status_id`) REFERENCES `paid_statuses` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `expenses_ibfk_bill` FOREIGN KEY (`bill_id`) REFERENCES `bills` (`id`) ON DELETE SET NULL,
  CONSTRAINT `expenses_ibfk_invoice` FOREIGN KEY (`invoice_id`) REFERENCES `invoices` (`id`) ON DELETE SET NULL,
  CONSTRAINT `expenses_ibfk_supplier` FOREIGN KEY (`supplier_id`) REFERENCES `suppliers` (`id`) ON DELETE SET NULL,
  CONSTRAINT `expenses_ibfk_expense_recurrence` FOREIGN KEY (`expense_recurrence_id`) REFERENCES `expense_recurrence` (`id`) ON DELETE SET NULL,
  CONSTRAINT `expenses_ibfk_recurrence_source` FOREIGN KEY (`recurrence_source_expense_id`) REFERENCES `expenses` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
