-- Portal accessibility: settings columns + physical room accessible_room flag.
-- Apply on existing DBs: php scripts/migrate.php --apply
-- Destructive: DROP removes hotel_booking_settings rows and dependent booking/room rows listed below.

DROP TABLE IF EXISTS `hotel_booking_distribution_reservations`;
DROP TABLE IF EXISTS `hotel_booking_payment_events`;
DROP TABLE IF EXISTS `hotel_bookings`;
DROP TABLE IF EXISTS `hotel_booking_housekeeping_maintenance`;
DROP TABLE IF EXISTS `hotel_booking_room_photos`;
DROP TABLE IF EXISTS `hotel_booking_room_utilities`;
DROP TABLE IF EXISTS `hotel_booking_rooms`;

CREATE TABLE `hotel_booking_rooms` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int NOT NULL,
  `hotel_id` int NOT NULL,
  `room_type_id` int NOT NULL,
  `housekeeping_status_id` int DEFAULT NULL,
  `room_number` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `floor` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `num_persons` int NOT NULL DEFAULT '2',
  `num_beds` int NOT NULL DEFAULT '1',
  `size_sqm` decimal(8,2) DEFAULT NULL,
  `view_label` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `connecting_room_id` int DEFAULT NULL,
  `connected_to` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `smoking_allowed` tinyint(1) NOT NULL DEFAULT '0',
  `accessible_room` tinyint(1) NOT NULL DEFAULT '0',
  `is_out_of_order` tinyint(1) NOT NULL DEFAULT '0',
  `is_out_of_service` tinyint(1) NOT NULL DEFAULT '0',
  `active` tinyint(1) DEFAULT '1',
  `deleted_by` int DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hotel_booking_rooms_company_hotel_number` (`company_id`,`hotel_id`,`room_number`),
  KEY `company_id` (`company_id`),
  KEY `hotel_id` (`hotel_id`),
  KEY `room_type_id` (`room_type_id`),
  KEY `housekeeping_status_id` (`housekeeping_status_id`),
  KEY `connecting_room_id` (`connecting_room_id`),
  CONSTRAINT `hotel_booking_rooms_ibfk_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `hotel_booking_rooms_ibfk_hotel` FOREIGN KEY (`hotel_id`) REFERENCES `hotel_booking_hotels` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `hotel_booking_rooms_ibfk_type` FOREIGN KEY (`room_type_id`) REFERENCES `booking_rooms_types` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `hotel_booking_rooms_ibfk_hk` FOREIGN KEY (`housekeeping_status_id`) REFERENCES `hotel_booking_housekeeping_statuses` (`id`) ON DELETE SET NULL,
  CONSTRAINT `hotel_booking_rooms_ibfk_connecting` FOREIGN KEY (`connecting_room_id`) REFERENCES `hotel_booking_rooms` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `hotel_bookings` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int NOT NULL,
  `customer_id` int NOT NULL,
  `room_id` int NOT NULL,
  `check_in` date NOT NULL,
  `check_out` date NOT NULL,
  `payment_amount` decimal(12,2) NOT NULL DEFAULT '0.00',
  `payment_status` enum('unpaid','pending','paid','refunded') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'unpaid',
  `stripe_checkout_session_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `stripe_payment_intent_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `amount_paid` decimal(12,2) NOT NULL DEFAULT '0.00',
  `guest_confirmation_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `auth2` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `future_status_id` int DEFAULT NULL,
  `present_status_id` int DEFAULT NULL,
  `history_status_id` int DEFAULT NULL,
  `portal_rate_plan_id` int DEFAULT NULL,
  `internal_rate_code` enum('','use','comp') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `notes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `booking_color` varchar(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `active` tinyint(1) DEFAULT '1',
  `deleted_by` int DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `company_id` (`company_id`),
  KEY `customer_id` (`customer_id`),
  KEY `room_id` (`room_id`),
  KEY `idx_hotel_bookings_dates` (`company_id`,`check_in`,`check_out`),
  KEY `future_status_id` (`future_status_id`),
  KEY `present_status_id` (`present_status_id`),
  KEY `history_status_id` (`history_status_id`),
  KEY `portal_rate_plan_id` (`portal_rate_plan_id`),
  UNIQUE KEY `uq_hotel_bookings_company_guest_confirmation` (`company_id`,`guest_confirmation_code`),
  CONSTRAINT `hotel_bookings_ibfk_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `hotel_bookings_ibfk_customer` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `hotel_bookings_ibfk_room` FOREIGN KEY (`room_id`) REFERENCES `hotel_booking_rooms` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `hotel_bookings_ibfk_future` FOREIGN KEY (`future_status_id`) REFERENCES `hotel_bookings_future` (`id`) ON DELETE SET NULL,
  CONSTRAINT `hotel_bookings_ibfk_present` FOREIGN KEY (`present_status_id`) REFERENCES `hotel_bookings_present` (`id`) ON DELETE SET NULL,
  CONSTRAINT `hotel_bookings_ibfk_history` FOREIGN KEY (`history_status_id`) REFERENCES `hotel_bookings_history` (`id`) ON DELETE SET NULL,
  CONSTRAINT `hotel_bookings_ibfk_portal_rate_plan` FOREIGN KEY (`portal_rate_plan_id`) REFERENCES `hotel_booking_portal_rate_plans` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `hotel_booking_settings`;

CREATE TABLE `hotel_booking_settings` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int NOT NULL,
  `public_portal_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `stripe_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `stripe_mode` enum('test','live') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'test',
  `stripe_publishable_key` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `stripe_secret_key_encrypted` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `stripe_webhook_signing_secret_encrypted` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `deposit_percent` decimal(5,2) NOT NULL DEFAULT '100.00',
  `welcome_title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `welcome_subtitle` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `accessible_features_default` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `airport_info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `price_footnote` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `reviews_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tourist_tax_per_person_per_night` decimal(10,2) NOT NULL DEFAULT '2.00',
  `free_cancellation_days_before_check_in` int NOT NULL DEFAULT '5',
  `calendar_month_advance_days_left` int NOT NULL DEFAULT '3',
  `show_discount_strikethrough` tinyint(1) NOT NULL DEFAULT '1',
  `portal_complimentary_min_rooms_paid` int NOT NULL DEFAULT '0',
  `portal_complimentary_rooms_free` int NOT NULL DEFAULT '1',
  `portal_confirmation_email_guest` tinyint(1) NOT NULL DEFAULT '1',
  `portal_confirmation_email_reservations` tinyint(1) NOT NULL DEFAULT '1',
  `portal_show_room_number_on_confirmation` tinyint(1) NOT NULL DEFAULT '0',
  `portal_hide_upgrade_upsell_when_multi_room` tinyint(1) NOT NULL DEFAULT '1',
  `portal_money_symbol` enum('EUR','GBP','USD') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'EUR',
  `portal_money_symbol_suffix` tinyint(1) NOT NULL DEFAULT '1',
  `portal_money_symbol_prefix` tinyint(1) NOT NULL DEFAULT '0',
  `portal_show_internal_rates` tinyint(1) NOT NULL DEFAULT '0',
  `portal_date_format` enum('european_ddmmyyyy','us_mmddyyyy','iso_yyyymmdd') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'european_ddmmyyyy',
  `portal_time_format` enum('h24','h12') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'h24',
  `portal_datetime_european1_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `portal_datetime_european2_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `portal_datetime_iso_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `portal_datetime_readable_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `portal_datetime_format_default` enum('european1','european2','iso','readable') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'european2',
  `portal_accessible_banner_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `portal_accessibility_options_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `urlaccessibilitypep` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'https://localhost/it-management/booking/accessibility/pep.html',
  `urlmybooking` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'https://localhost/it-management/booking/users/bookings.php',
  `active` tinyint(1) DEFAULT '1',
  `deleted_by` int DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hotel_booking_settings_company` (`company_id`),
  CONSTRAINT `hotel_booking_settings_ibfk_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `hotel_booking_settings` (`company_id`, `public_portal_enabled`, `stripe_enabled`, `stripe_mode`, `deposit_percent`, `tourist_tax_per_person_per_night`, `free_cancellation_days_before_check_in`, `calendar_month_advance_days_left`, `show_discount_strikethrough`, `portal_accessible_banner_enabled`, `portal_accessibility_options_enabled`, `urlaccessibilitypep`, `urlmybooking`, `active`, `created_at`)
SELECT c.`id`, 0, 0, 'test', 100.00, 2.00, 5, 3, 1, 1, 1, 'https://localhost/it-management/booking/accessibility/pep.html', 'https://localhost/it-management/booking/users/bookings.php', 1, NOW()
FROM `companies` c;
