-- Portal UI copy — four satellite tables (267 portal_ui_* TEXT columns; InnoDB row-size limit).
-- Apply: php scripts/migrate.php --apply
-- Non-destructive to hotel_booking_settings; seeds one row per company per table.


DROP TABLE IF EXISTS `hotel_booking_portal_ui_copy_home`;
CREATE TABLE `hotel_booking_portal_ui_copy_home` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int NOT NULL,
  `portal_ui_home_welcome_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_from_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_details_button` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_view_details_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_loading` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_dates_heading` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_amenity_wifi_fallback` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_amenity_pool_fallback` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_amenity_fitness_fallback` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_parking_self_fallback` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_parking_valet_fallback` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_nearby_empty` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_airport_empty` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_price_footnote_fallback` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_favorite_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_favorite_aria_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_directions_link` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_visit_website_link` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_info_link` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_email_link` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_description_heading` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_read_more` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_read_less` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_overview_heading` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_amenities_heading` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_check_in_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_check_out_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_currency_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_parking_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_pets_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_currency_euro_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_location_heading` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_nearby_tab` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_airport_tab` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_accessible_features_heading` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_select_dates_button` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_select_dates_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_read_reviews_link` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_read_reviews_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_guest_rating_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_guest_rating_subtitle` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_default_rate_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_price_includes_tax_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_dates_select_copy` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_home_dates_price_copy` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_chrome_brand_fallback` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_chrome_night_singular` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_chrome_nights_plural` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_chrome_room_suffix` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_chrome_logout_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_chrome_edit_stay_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_chrome_stay_bar_hotel_tooltip` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_chrome_stay_bar_dates_tooltip` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_chrome_stay_bar_occupancy_change_tooltip` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_chrome_stay_bar_occupancy_readonly_tooltip` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_chrome_manage_booking_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_chrome_step_progress_template` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `active` tinyint(1) DEFAULT '1',
  `deleted_by` int DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hotel_booking_portal_ui_copy_home_company` (`company_id`),
  CONSTRAINT `hotel_booking_portal_ui_copy_home_ibfk_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `hotel_booking_portal_ui_copy_step1`;
CREATE TABLE `hotel_booking_portal_ui_copy_step1` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int NOT NULL,
  `portal_ui_step1_room_not_available` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_filter_king_bed` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_filter_twin_beds` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_filter_queen_bed` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_filter_garden_view` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_filter_city_view` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_filter_balcony` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_filter_accessible` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_filter_smoking` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_multi_room_banner_lead` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_multi_room_banner_types_hint` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_multi_room_slot_guests` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_multi_room_slot_room` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_room_filters_button` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_special_rates_button` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_room_types_found` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_room_types_sold_out` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_sold_out_badge` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_sold_out_capacity` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_sold_out_dates` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_sold_out_mixed_types` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_connecting_room_card_banner` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_connecting_room_detail_banner` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_per_night_suffix` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_select_button` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_not_available_button` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_hotel_details_link` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_occupancy_modal_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_occupancy_rooms_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_occupancy_adults_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_occupancy_children_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_occupancy_babies_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_occupancy_modal_note` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_apply_button` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_filters_modal_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_apply_filters_button` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_clear_filters_button` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_standard_rate_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_internal_rate_price_zero_suffix` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_rate_program_use_points` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_rate_program_travel_agents` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_rate_program_aaa` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_rate_program_senior` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_rate_program_government` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_code_rate_promo` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_code_rate_group` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_code_rate_corporate` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_code_rate_member` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_internal_rate_use_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_internal_rate_comp_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_view_room_details` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_direct_book_banner` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_accessible_room_banner` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_policy_adults_only` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_policy_smoking` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_policy_accessible` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_policy_crib` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_policy_extra_bed` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_highlight_guests` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_highlight_room_layout` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_highlight_bathroom` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_highlight_kitchen` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_hotel_amenities_heading` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_room_highlights_heading` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_more_room_details` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_for_your_comfort` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_book_from_prefix` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_book_room_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_room_desc_lead_default` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_room_desc_extra_default` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_room_spec_default` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_room_types_shown` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step1_amenity_pool_fallback` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `active` tinyint(1) DEFAULT '1',
  `deleted_by` int DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hotel_booking_portal_ui_copy_step1_company` (`company_id`),
  CONSTRAINT `hotel_booking_portal_ui_copy_step1_ibfk_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `hotel_booking_portal_ui_copy_checkout`;
CREATE TABLE `hotel_booking_portal_ui_copy_checkout` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int NOT NULL,
  `portal_ui_step2_select_rate_error` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step2_breakfast_disclaimer_template` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step2_tourist_tax_note` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step2_tourist_tax_note_multi_room` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step2_no_rate_plans` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step2_breakfast_not_included` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step2_breakfast_addon_template` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_shared_per_night` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step2_stay_total_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step2_select_button` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step2_your_rooms_heading` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step2_pay_badge_pay_at_hotel` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step2_pay_badge_non_refundable` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step2_back_button` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step3_pep_error` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step3_upgrade_heading` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step3_upgrade_pitch_default` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_shared_per_night_meta` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step3_special_requests_heading` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step3_no_special_requests` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step3_traveling_with_pet` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step3_pet_policy_template` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step3_service_animal` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step3_accessibility_heading` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step3_accessibility_need_prompt` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step3_pep_intro` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step3_pep_document_link` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step3_pep_ack_checkbox` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step3_comments_placeholder` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_shared_guarantee_disclaimer` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step3_continue_button` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step3_continue_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step3_accessibility_none` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step3_accessibility_mobility` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step3_accessibility_hearing` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step3_accessibility_visual` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step3_accessibility_cognitive` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step3_accessibility_other` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step3_additional_comments_heading` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step4_session_expired` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step4_name_email_required` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step4_invalid_email` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step4_invalid_phone` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step4_invalid_dates` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step4_pricing_error` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step4_save_guest_error` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step4_booking_failed` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step4_total_due_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step4_full_name_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step4_email_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step4_phone_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step4_phone_hint` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step4_payment_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step4_pay_stripe` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step4_pay_at_hotel` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step4_check_in_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step4_check_out_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step4_agreement_text` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step4_agree_checkbox` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step4_book_reservation_button` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step4_terms_alert` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_step4_back_button` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `active` tinyint(1) DEFAULT '1',
  `deleted_by` int DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hotel_booking_portal_ui_copy_checkout_company` (`company_id`),
  CONSTRAINT `hotel_booking_portal_ui_copy_checkout_ibfk_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `hotel_booking_portal_ui_copy_confirm`;
CREATE TABLE `hotel_booking_portal_ui_copy_confirm` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int NOT NULL,
  `portal_ui_confirm_reservation_summary_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_subject_to_approval` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_rate_prefix` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_change_rate_link` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_complimentary_credit` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_total_room_charges` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_traveling_with_pet` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_total_taxes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_total_for_stay` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_tax_per_person_suffix` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_room_slot_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_your_rooms_heading` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_reservation_confirmed_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_reservation_cancelled_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_lead_confirmed` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_lead_cancelled` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_lead_cancelled_named` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_confirmation_number` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_auth_code` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_status_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_status_cancelled` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_guests_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_room_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_rate_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_number_of_nights` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_total_for_stay_detail` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_payment_received` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_payment_received_body` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_payment_pending_lead` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_payment_pending_body` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_payment_options_lead` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_payment_options_body` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_payment_at_hotel_lead` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_payment_at_hotel_body` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_manage_hint_template` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_save_pdf_button` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_return_home` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_cancelled_notice` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_your_reservation_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_reservation_notes_heading` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_guest_comments_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_pet_hint_daily_fee` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_cancellation_policy_button` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_cancellation_loading` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_cancellation_load_fail` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_change_booking_button` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_change_booking_modal_note` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_cancel_booking_button` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_cancel_confirm_prompt` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_cancel_already_cancelled` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_cancel_not_available` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_change_room_link` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_stripe_success` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_stripe_cancel` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_stripe_error` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_confirm_cancel_success` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_manage_lookup_intro` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_manage_last_name_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_manage_confirmation_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_manage_auth_code_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_manage_find_reservation_button` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_manage_otp_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_manage_otp_intro` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_manage_otp_code_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_manage_otp_placeholder` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_manage_verify_button` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_manage_back_button` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_manage_lookup_failure` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_manage_invalid_otp` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_manage_verification_failure` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_manage_rate_limit` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_manage_otp_rate_limit` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_manage_missing_fields` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_manage_cancel_requires_otp` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_ui_manage_cancel_failed` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `active` tinyint(1) DEFAULT '1',
  `deleted_by` int DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hotel_booking_portal_ui_copy_confirm_company` (`company_id`),
  CONSTRAINT `hotel_booking_portal_ui_copy_confirm_ibfk_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `hotel_booking_portal_ui_copy_home` (`company_id`, `created_at`)
SELECT c.`id`, NOW() FROM `companies` c
WHERE NOT EXISTS (SELECT 1 FROM `hotel_booking_portal_ui_copy_home` t WHERE t.`company_id` = c.`id`);

INSERT INTO `hotel_booking_portal_ui_copy_step1` (`company_id`, `created_at`)
SELECT c.`id`, NOW() FROM `companies` c
WHERE NOT EXISTS (SELECT 1 FROM `hotel_booking_portal_ui_copy_step1` t WHERE t.`company_id` = c.`id`);

INSERT INTO `hotel_booking_portal_ui_copy_checkout` (`company_id`, `created_at`)
SELECT c.`id`, NOW() FROM `companies` c
WHERE NOT EXISTS (SELECT 1 FROM `hotel_booking_portal_ui_copy_checkout` t WHERE t.`company_id` = c.`id`);

INSERT INTO `hotel_booking_portal_ui_copy_confirm` (`company_id`, `created_at`)
SELECT c.`id`, NOW() FROM `companies` c
WHERE NOT EXISTS (SELECT 1 FROM `hotel_booking_portal_ui_copy_confirm` t WHERE t.`company_id` = c.`id`);

