-- Portal display/maps/occupancy settings.
-- Apply: php scripts/migrate.php --apply
-- Destructive: DROP removes existing hotel_booking_settings rows (re-seeded per company).

DROP TABLE IF EXISTS `hotel_booking_settings`;

CREATE TABLE `hotel_booking_settings` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int NOT NULL,
  `public_portal_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `stripe_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `stripe_mode` enum('test','live') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'test',
  `stripe_publishable_key` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `stripe_secret_key_encrypted` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `stripe_webhook_signing_secret_encrypted` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `deposit_percent` decimal(5,2) NOT NULL DEFAULT '100.00',
  `welcome_title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `welcome_subtitle` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `accessible_features_default` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `airport_info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `price_footnote` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `reviews_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tourist_tax_per_person_per_night` decimal(10,2) NOT NULL DEFAULT '2.00',
  `portal_max_discount_percent` decimal(5,2) NOT NULL DEFAULT '50.00',
  `portal_tourist_tax_label` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Tourist tax',
  `portal_price_includes_tax_label` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'incl. tax',
  `portal_price_includes_tax_long_label` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'incl. taxes',
  `portal_default_rate_label` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Best available rate',
  `portal_breakfast_rate_label` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Breakfast included',
  `portal_default_pet_max_weight_kg` int NOT NULL DEFAULT '30',
  `portal_maps_base_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'https://maps.google.com/?q=',
  `portal_calendar_month_horizon` int NOT NULL DEFAULT '14',
  `portal_phone_example` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '+351912345678',
  `portal_direct_book_banner_text` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Book direct for the best available rate and flexible stay options.',
  `portal_rating_title` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Guest rating',
  `portal_rating_subtitle` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT ' — based on recent stays',
  `portal_step_label_room` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `portal_step_label_rate` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Select a Rate',
  `portal_step_label_customize` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Customize Your Stay',
  `portal_step_label_payment` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Payment and Guest Details',
  `portal_default_room_image_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '/images/room-5.jpg',
  `portal_room_type_code_fallback_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `portal_occupancy_max_rooms` int NOT NULL DEFAULT '4',
  `portal_occupancy_max_adults` int NOT NULL DEFAULT '12',
  `portal_occupancy_max_children` int NOT NULL DEFAULT '6',
  `portal_occupancy_max_babies` int NOT NULL DEFAULT '3',
  `portal_default_included_adults_per_room` int NOT NULL DEFAULT '2',
  `free_cancellation_days_before_check_in` int NOT NULL DEFAULT '5',
  `calendar_month_advance_days_left` int NOT NULL DEFAULT '3',
  `show_discount_strikethrough` tinyint(1) NOT NULL DEFAULT '1',
  `portal_complimentary_min_rooms_paid` int NOT NULL DEFAULT '0',
  `portal_complimentary_rooms_free` int NOT NULL DEFAULT '1',
  `portal_confirmation_email_guest` tinyint(1) NOT NULL DEFAULT '1',
  `portal_confirmation_email_reservations` tinyint(1) NOT NULL DEFAULT '1',
  `portal_show_room_number_on_confirmation` tinyint(1) NOT NULL DEFAULT '0',
  `portal_hide_upgrade_upsell_when_multi_room` tinyint(1) NOT NULL DEFAULT '1',
  `portal_money_symbol` enum('EUR','GBP','USD') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'EUR',
  `portal_money_symbol_suffix` tinyint(1) NOT NULL DEFAULT '1',
  `portal_money_symbol_prefix` tinyint(1) NOT NULL DEFAULT '0',
  `portal_show_internal_rates` tinyint(1) NOT NULL DEFAULT '0',
  `portal_date_format` enum('european_ddmmyyyy','us_mmddyyyy','iso_yyyymmdd') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'european_ddmmyyyy',
  `portal_time_format` enum('h24','h12') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'h24',
  `portal_datetime_european1_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `portal_datetime_european2_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `portal_datetime_iso_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `portal_datetime_readable_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `portal_datetime_format_default` enum('european1','european2','iso','readable') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'european2',
  `portal_accessible_banner_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `portal_accessibility_options_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `urlaccessibilitypep` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'https://localhost/it-management/booking/accessibility/pep.html',
  `urlmybooking` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'https://localhost/it-management/booking/users/bookings.php',
  `active` tinyint(1) DEFAULT '1',
  `deleted_by` int DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hotel_booking_settings_company` (`company_id`),
  CONSTRAINT `hotel_booking_settings_ibfk_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `hotel_booking_settings` (`company_id`, `public_portal_enabled`, `stripe_enabled`, `stripe_mode`, `deposit_percent`, `tourist_tax_per_person_per_night`, `portal_max_discount_percent`, `portal_tourist_tax_label`, `portal_price_includes_tax_label`, `portal_price_includes_tax_long_label`, `portal_default_rate_label`, `portal_breakfast_rate_label`, `portal_default_pet_max_weight_kg`, `portal_room_type_code_fallback_json`, `free_cancellation_days_before_check_in`, `calendar_month_advance_days_left`, `show_discount_strikethrough`, `portal_accessible_banner_enabled`, `portal_accessibility_options_enabled`, `urlaccessibilitypep`, `urlmybooking`, `active`, `created_at`)
SELECT c.`id`, 0, 0, 'test', 100.00, 2.00, 50.00, 'Tourist tax', 'incl. tax', 'incl. taxes', 'Best available rate', 'Breakfast included', 30, '{"DLX":"/images/room-5.jpg","STD":"/images/room-3.jpg","SUP":"/images/room-6.jpg"}', 5, 3, 1, 1, 1, 'https://localhost/it-management/booking/accessibility/pep.html', 'https://localhost/it-management/booking/users/bookings.php', 1, NOW()
FROM `companies` c;

