<?php
/**
 * Build db/02_data_sample.sql from db/02_data.sql (company 1 template rows only).
 *
 * Browser + CLI; dry-run by default. Writes with --apply or browser ?apply=1 (Admin).
 */
require_once __DIR__ . '/lib/itm_apply_script_bootstrap.php';

$ctx = itm_apply_script_bootstrap('Extract 02_data_sample.sql');
$isCli = $ctx['is_cli'];
$apply = $ctx['apply'];
$nl = $ctx['nl'];
$root = $ctx['root'];

$templateCompanyId = defined('ITM_SAMPLE_SQL_TEMPLATE_COMPANY_ID')
    ? (int)ITM_SAMPLE_SQL_TEMPLATE_COMPANY_ID
    : 1;

$sourcePath = itm_database_sql_data_path();
$targetPath = itm_database_sql_sample_path();

if (!is_readable($sourcePath)) {
    echo '[FAIL] Source not readable: ' . $sourcePath . $nl;
    exit(1);
}

$sqlBody = itm_database_sql_read_data();
if ($sqlBody === '') {
    echo '[FAIL] db/02_data.sql is empty.' . $nl;
    exit(1);
}

if (!function_exists('itm_parse_database_sql_inserts')) {
    echo '[FAIL] itm_parse_database_sql_inserts() is unavailable.' . $nl;
    exit(1);
}

$parsed = itm_parse_database_sql_inserts($sqlBody);
$tableCount = count($parsed);
$rowCount = 0;
$lines = [];
$lines[] = '-- ITM runtime sample templates for Add sample data and MBQA sample_data step.';
$lines[] = '-- NOT imported by scripts/import_database_split.sh — use db/02_data.sql for fresh installs.';
$lines[] = '-- Rows with company_id = ' . $templateCompanyId . ' are parse markers only; the seeder stamps the active tenant.';
$lines[] = '-- Generated by scripts/extract_02_data_sample.php from db/02_data.sql.';
$lines[] = '';

foreach ($parsed as $tableName => $insertRows) {
    if (!itm_is_safe_identifier($tableName)) {
        continue;
    }

    $keptRows = [];
    foreach ($insertRows as $rowEntry) {
        $rawColumns = $rowEntry['columns'] ?? [];
        $rawValues = $rowEntry['values'] ?? [];
        $companyIndex = null;
        foreach ($rawColumns as $index => $columnToken) {
            $columnName = trim((string)$columnToken, "` \t\n\r\0\x0B");
            if ($columnName === 'company_id') {
                $companyIndex = $index;
                break;
            }
        }

        if ($companyIndex === null) {
            $keptRows[] = $rowEntry;
            continue;
        }

        $rawCompanyToken = trim((string)($rawValues[$companyIndex] ?? ''));
        if ($rawCompanyToken === '' || strtoupper($rawCompanyToken) === 'NULL') {
            continue;
        }
        $rawCompanyToken = trim($rawCompanyToken, "'\"");
        if ((int)$rawCompanyToken === $templateCompanyId) {
            $keptRows[] = $rowEntry;
        }
    }

    if ($keptRows === []) {
        continue;
    }

    $columnsSql = implode(', ', array_map(static function ($col): string {
        $name = trim((string)$col, "` \t\n\r\0\x0B");

        return '`' . str_replace('`', '``', $name) . '`';
    }, $keptRows[0]['columns']));

    $valueTuples = [];
    foreach ($keptRows as $rowEntry) {
        $valueTuples[] = '(' . implode(', ', $rowEntry['values']) . ')';
        $rowCount++;
    }

    $lines[] = 'INSERT INTO `' . str_replace('`', '``', $tableName) . '` (' . $columnsSql . ') VALUES';
    $lines[] = implode(",\n", $valueTuples) . ';';
    $lines[] = '';
}

$output = implode("\n", $lines);
$outputSize = strlen($output);

echo 'Source: ' . $sourcePath . $nl;
echo 'Target: ' . $targetPath . $nl;
echo 'Tables with template rows: ' . $tableCount . ' parsed; output tables: ' . substr_count($output, 'INSERT INTO') . $nl;
echo 'Template rows (company_id=' . $templateCompanyId . ' or no company_id): ' . $rowCount . $nl;
echo 'Output size: ' . number_format($outputSize) . ' bytes' . $nl;

if (!$apply) {
    echo $nl . 'Dry-run — pass --apply (CLI) or ?apply=1 (browser Admin) to write.' . $nl;
    exit(0);
}

if (file_put_contents($targetPath, $output) === false) {
    echo '[FAIL] Could not write ' . $targetPath . $nl;
    exit(1);
}

echo '[OK] Wrote ' . $targetPath . $nl;
exit(0);
