<?php
/**
 * Audit Logs Module - Create Placeholder
 *
 * Why: Audit records are generated by database triggers to preserve an
 * immutable chain of evidence, so manual creation must stay unavailable.
 */

require '../../config/config.php';

header('Location: index.php');
exit;
