<?php
/**
 * Default guest-facing copy for the public hotel booking portal.
 *
 * Each row maps to a `portal_ui_*` column on `hotel_booking_settings` (or companion
 * admin UI). Identical strings share one column name across sections (e.g. Read reviews).
 *
 * @return list<array{column:string,default:string,maxlen:int|string,section:string,label:string,placeholders?:list<string>,required?:bool}>
 */
return [
    // --- home ---
    [
        'column' => 'portal_ui_home_welcome_title',
        'default' => 'Find your stay',
        'maxlen' => 80,
        'section' => 'home',
        'label' => 'Home page title (welcome)',
    ],
    [
        'column' => 'portal_ui_home_from_label',
        'default' => 'From',
        'maxlen' => 40,
        'section' => 'home',
        'label' => 'Hotel card price prefix',
    ],
    [
        'column' => 'portal_ui_home_details_button',
        'default' => 'Details',
        'maxlen' => 40,
        'section' => 'home',
        'label' => 'Hotel card details button',
    ],
    [
        'column' => 'portal_ui_home_view_details_title',
        'default' => 'View details',
        'maxlen' => 80,
        'section' => 'home',
        'label' => 'Hotel card details button tooltip',
    ],
    [
        'column' => 'portal_ui_home_loading',
        'default' => 'Loading…',
        'maxlen' => 40,
        'section' => 'home',
        'label' => 'Hotel detail modal loading text',
    ],
    [
        'column' => 'portal_ui_home_dates_heading',
        'default' => 'Find the best prices for your next trip',
        'maxlen' => 255,
        'section' => 'home',
        'label' => 'Dates modal heading',
    ],
    [
        'column' => 'portal_ui_home_amenity_wifi_fallback',
        'default' => 'Free WiFi',
        'maxlen' => 80,
        'section' => 'home',
        'label' => 'Amenity fallback — WiFi',
    ],
    [
        'column' => 'portal_ui_home_amenity_pool_fallback',
        'default' => 'Indoor pool',
        'maxlen' => 80,
        'section' => 'home',
        'label' => 'Amenity fallback — pool (home modal)',
    ],
    [
        'column' => 'portal_ui_home_amenity_fitness_fallback',
        'default' => 'Fitness center',
        'maxlen' => 80,
        'section' => 'home',
        'label' => 'Amenity fallback — fitness',
    ],
    [
        'column' => 'portal_ui_home_parking_self_fallback',
        'default' => 'Self parking: Complimentary',
        'maxlen' => 255,
        'section' => 'home',
        'label' => 'Parking fallback — self',
    ],
    [
        'column' => 'portal_ui_home_parking_valet_fallback',
        'default' => 'Valet parking: Complimentary',
        'maxlen' => 255,
        'section' => 'home',
        'label' => 'Parking fallback — valet',
    ],
    [
        'column' => 'portal_ui_home_nearby_empty',
        'default' => 'No places listed.',
        'maxlen' => 255,
        'section' => 'home',
        'label' => 'Nearby list empty state',
    ],
    [
        'column' => 'portal_ui_home_airport_empty',
        'default' => 'No airport information.',
        'maxlen' => 255,
        'section' => 'home',
        'label' => 'Airport list empty state',
    ],
    [
        'column' => 'portal_ui_home_price_footnote_fallback',
        'default' => '*Prices are based on current availability and may change.',
        'maxlen' => 500,
        'section' => 'home',
        'label' => 'Price footnote (hotel modal)',
    ],
    [
        'column' => 'portal_ui_home_favorite_title',
        'default' => 'Save to favorites',
        'maxlen' => 80,
        'section' => 'home',
        'label' => 'Favorite button tooltip',
    ],
    [
        'column' => 'portal_ui_home_favorite_aria_label',
        'default' => 'Favorite',
        'maxlen' => 40,
        'section' => 'home',
        'label' => 'Favorite button aria-label',
    ],
    [
        'column' => 'portal_ui_home_directions_link',
        'default' => 'Directions',
        'maxlen' => 40,
        'section' => 'home',
        'label' => 'Directions action link',
    ],
    [
        'column' => 'portal_ui_home_visit_website_link',
        'default' => 'Visit website',
        'maxlen' => 80,
        'section' => 'home',
        'label' => 'Visit website action link',
    ],
    [
        'column' => 'portal_ui_home_info_link',
        'default' => 'Info',
        'maxlen' => 40,
        'section' => 'home',
        'label' => 'General info email link',
    ],
    [
        'column' => 'portal_ui_home_email_link',
        'default' => 'Email',
        'maxlen' => 40,
        'section' => 'home',
        'label' => 'Reservations email link',
    ],
    [
        'column' => 'portal_ui_home_description_heading',
        'default' => 'Description',
        'maxlen' => 40,
        'section' => 'home',
        'label' => 'Description section heading',
    ],
    [
        'column' => 'portal_ui_home_read_more',
        'default' => 'Read more',
        'maxlen' => 40,
        'section' => 'home',
        'label' => 'Read more toggle',
    ],
    [
        'column' => 'portal_ui_home_read_less',
        'default' => 'Read less',
        'maxlen' => 40,
        'section' => 'home',
        'label' => 'Read less toggle',
    ],
    [
        'column' => 'portal_ui_home_overview_heading',
        'default' => 'Overview',
        'maxlen' => 40,
        'section' => 'home',
        'label' => 'Overview section heading',
    ],
    [
        'column' => 'portal_ui_home_amenities_heading',
        'default' => 'Amenities',
        'maxlen' => 40,
        'section' => 'home',
        'label' => 'Amenities section heading',
    ],
    [
        'column' => 'portal_ui_home_check_in_label',
        'default' => 'Check-in',
        'maxlen' => 40,
        'section' => 'home',
        'label' => 'Overview check-in label',
    ],
    [
        'column' => 'portal_ui_home_check_out_label',
        'default' => 'Check-out',
        'maxlen' => 40,
        'section' => 'home',
        'label' => 'Overview check-out label',
    ],
    [
        'column' => 'portal_ui_home_currency_label',
        'default' => 'Currency',
        'maxlen' => 40,
        'section' => 'home',
        'label' => 'Overview currency label',
    ],
    [
        'column' => 'portal_ui_home_parking_label',
        'default' => 'Parking',
        'maxlen' => 40,
        'section' => 'home',
        'label' => 'Overview parking label',
    ],
    [
        'column' => 'portal_ui_home_pets_label',
        'default' => 'Pets',
        'maxlen' => 40,
        'section' => 'home',
        'label' => 'Overview pets label',
    ],
    [
        'column' => 'portal_ui_home_currency_euro_label',
        'default' => 'Euro',
        'maxlen' => 40,
        'section' => 'home',
        'label' => 'Currency display name for EUR',
    ],
    [
        'column' => 'portal_ui_home_location_heading',
        'default' => 'Location and transportation',
        'maxlen' => 255,
        'section' => 'home',
        'label' => 'Location section heading',
    ],
    [
        'column' => 'portal_ui_home_nearby_tab',
        'default' => "What's nearby",
        'maxlen' => 80,
        'section' => 'home',
        'label' => 'Nearby places tab label',
    ],
    [
        'column' => 'portal_ui_home_airport_tab',
        'default' => 'Airport info',
        'maxlen' => 80,
        'section' => 'home',
        'label' => 'Airport info tab label',
    ],
    [
        'column' => 'portal_ui_home_accessible_features_heading',
        'default' => 'Accessible features',
        'maxlen' => 80,
        'section' => 'home',
        'label' => 'Accessible features accordion heading',
    ],
    [
        'column' => 'portal_ui_home_select_dates_button',
        'default' => 'Select Dates',
        'maxlen' => 40,
        'section' => 'home',
        'label' => 'Select dates CTA button',
    ],
    [
        'column' => 'portal_ui_home_select_dates_title',
        'default' => 'Select dates',
        'maxlen' => 80,
        'section' => 'home',
        'label' => 'Select dates CTA tooltip',
    ],
    [
        'column' => 'portal_ui_home_read_reviews_link',
        'default' => 'Read reviews',
        'maxlen' => 80,
        'section' => 'home',
        'label' => 'Read reviews link text (shared with chrome)',
    ],
    [
        'column' => 'portal_ui_home_read_reviews_title',
        'default' => 'Read reviews (opens in new tab)',
        'maxlen' => 255,
        'section' => 'home',
        'label' => 'Read reviews link tooltip (shared with chrome)',
    ],
    [
        'column' => 'portal_ui_home_guest_rating_title',
        'default' => 'Guest rating',
        'maxlen' => 80,
        'section' => 'home',
        'label' => 'Guest rating title',
    ],
    [
        'column' => 'portal_ui_home_guest_rating_subtitle',
        'default' => ' — based on recent stays',
        'maxlen' => 255,
        'section' => 'home',
        'label' => 'Guest rating subtitle',
    ],
    [
        'column' => 'portal_ui_home_default_rate_label',
        'default' => 'Best available rate',
        'maxlen' => 80,
        'section' => 'home',
        'label' => 'Cheapest rate label fallback',
    ],
    [
        'column' => 'portal_ui_home_price_includes_tax_label',
        'default' => 'incl. tax',
        'maxlen' => 40,
        'section' => 'home',
        'label' => 'Price includes tax short label',
    ],
    [
        'column' => 'portal_ui_home_dates_select_copy',
        'default' => 'Select your check-in date, then your check-out date. One night is selected when only check-in is chosen.',
        'maxlen' => 500,
        'section' => 'home',
        'label' => 'Dates modal — how to select dates',
    ],
    [
        'column' => 'portal_ui_home_dates_price_copy',
        'default' => "We're showing the best price per room based on the number of guests. Prices include tourist tax and fees.",
        'maxlen' => 500,
        'section' => 'home',
        'label' => 'Dates modal — pricing explanation',
    ],

    // --- chrome ---
    [
        'column' => 'portal_ui_chrome_brand_fallback',
        'default' => 'Hotel booking',
        'maxlen' => 80,
        'section' => 'chrome',
        'label' => 'Header brand fallback',
    ],
    [
        'column' => 'portal_ui_chrome_night_singular',
        'default' => 'night',
        'maxlen' => 40,
        'section' => 'chrome',
        'label' => 'Stay bar — night (singular)',
    ],
    [
        'column' => 'portal_ui_chrome_nights_plural',
        'default' => 'nights',
        'maxlen' => 40,
        'section' => 'chrome',
        'label' => 'Stay bar — nights (plural)',
    ],
    [
        'column' => 'portal_ui_chrome_room_suffix',
        'default' => 'Room',
        'maxlen' => 40,
        'section' => 'chrome',
        'label' => 'Reservation room title suffix',
    ],
    [
        'column' => 'portal_ui_chrome_logout_label',
        'default' => 'Logout',
        'maxlen' => 40,
        'section' => 'chrome',
        'label' => 'Stay bar logout action',
    ],
    [
        'column' => 'portal_ui_chrome_edit_stay_label',
        'default' => 'Edit stay',
        'maxlen' => 40,
        'section' => 'chrome',
        'label' => 'Stay bar edit-stay action',
    ],
    [
        'column' => 'portal_ui_chrome_stay_bar_hotel_tooltip',
        'default' => 'Hotel',
        'maxlen' => 40,
        'section' => 'chrome',
        'label' => 'Stay bar hotel tooltip',
    ],
    [
        'column' => 'portal_ui_chrome_stay_bar_dates_tooltip',
        'default' => 'Dates',
        'maxlen' => 40,
        'section' => 'chrome',
        'label' => 'Stay bar dates tooltip',
    ],
    [
        'column' => 'portal_ui_chrome_stay_bar_occupancy_change_tooltip',
        'default' => 'Change rooms and guests',
        'maxlen' => 80,
        'section' => 'chrome',
        'label' => 'Stay bar occupancy change tooltip',
    ],
    [
        'column' => 'portal_ui_chrome_stay_bar_occupancy_readonly_tooltip',
        'default' => 'Rooms and guests',
        'maxlen' => 80,
        'section' => 'chrome',
        'label' => 'Stay bar occupancy readonly tooltip',
    ],
    [
        'column' => 'portal_ui_chrome_manage_booking_label',
        'default' => 'Manage my booking',
        'maxlen' => 80,
        'section' => 'chrome',
        'label' => 'Header manage-booking nav link',
    ],
    [
        'column' => 'portal_ui_chrome_step_progress_template',
        'default' => 'Step {step} of {total}',
        'maxlen' => 80,
        'section' => 'chrome',
        'label' => 'Checkout step progress label',
        'placeholders' => ['{step}', '{total}'],
    ],

    // --- step1 ---
    [
        'column' => 'portal_ui_step1_room_not_available',
        'default' => 'Room not available.',
        'maxlen' => 255,
        'section' => 'step1',
        'label' => 'Multi-room pick error',
    ],
    [
        'column' => 'portal_ui_step1_filter_king_bed',
        'default' => 'King bed',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room filter — king bed',
    ],
    [
        'column' => 'portal_ui_step1_filter_twin_beds',
        'default' => 'Twin beds',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room filter — twin beds',
    ],
    [
        'column' => 'portal_ui_step1_filter_queen_bed',
        'default' => 'Queen bed',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room filter — queen bed',
    ],
    [
        'column' => 'portal_ui_step1_filter_garden_view',
        'default' => 'Garden view',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room filter — garden view',
    ],
    [
        'column' => 'portal_ui_step1_filter_city_view',
        'default' => 'City view',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room filter — city view',
    ],
    [
        'column' => 'portal_ui_step1_filter_balcony',
        'default' => 'Balcony',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room filter — balcony',
    ],
    [
        'column' => 'portal_ui_step1_filter_accessible',
        'default' => 'Accessible room',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room filter — accessible',
    ],
    [
        'column' => 'portal_ui_step1_filter_smoking',
        'default' => 'Smoking allowed',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room filter — smoking',
    ],
    [
        'column' => 'portal_ui_step1_multi_room_banner_lead',
        'default' => 'Room {current} of {total} — choose a room, then select a rate. Repeat until all rooms are rated.',
        'maxlen' => 500,
        'section' => 'step1',
        'label' => 'Multi-room banner lead',
        'placeholders' => ['{current}', '{total}'],
    ],
    [
        'column' => 'portal_ui_step1_multi_room_banner_types_hint',
        'default' => ' Types already chosen with no more units show as unavailable — pick a different room type.',
        'maxlen' => 500,
        'section' => 'step1',
        'label' => 'Multi-room banner mixed-types hint',
    ],
    [
        'column' => 'portal_ui_step1_multi_room_slot_guests',
        'default' => 'Room {room} guests:',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Multi-room occupancy split label',
        'placeholders' => ['{room}'],
    ],
    [
        'column' => 'portal_ui_step1_multi_room_slot_room',
        'default' => 'Room {room}:',
        'maxlen' => 40,
        'section' => 'step1',
        'label' => 'Multi-room picked room label',
        'placeholders' => ['{room}'],
    ],
    [
        'column' => 'portal_ui_step1_room_filters_button',
        'default' => 'Room Filters',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room filters toolbar button',
    ],
    [
        'column' => 'portal_ui_step1_special_rates_button',
        'default' => 'Special rates',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Special rates toolbar button',
    ],
    [
        'column' => 'portal_ui_step1_room_types_found',
        'default' => '{count} room types found.',
        'maxlen' => 255,
        'section' => 'step1',
        'label' => 'Inventory count — types found',
        'placeholders' => ['{count}'],
    ],
    [
        'column' => 'portal_ui_step1_room_types_sold_out',
        'default' => '{count} are currently sold out.',
        'maxlen' => 255,
        'section' => 'step1',
        'label' => 'Inventory count — sold out',
        'placeholders' => ['{count}'],
    ],
    [
        'column' => 'portal_ui_step1_sold_out_badge',
        'default' => 'Sold out',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Sold-out badge — default',
    ],
    [
        'column' => 'portal_ui_step1_sold_out_capacity',
        'default' => 'Guests exceed capacity',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Sold-out badge — capacity',
    ],
    [
        'column' => 'portal_ui_step1_sold_out_dates',
        'default' => 'Not available for these dates',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Sold-out badge — dates',
    ],
    [
        'column' => 'portal_ui_step1_sold_out_mixed_types',
        'default' => 'Same room type required',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Sold-out badge — mixed types',
    ],
    [
        'column' => 'portal_ui_step1_connecting_room_card_banner',
        'default' => 'Includes connecting room {room} — booked as one unit',
        'maxlen' => 255,
        'section' => 'step1',
        'label' => 'Connecting room card banner',
        'placeholders' => ['{room}'],
    ],
    [
        'column' => 'portal_ui_step1_connecting_room_detail_banner',
        'default' => 'Connecting rooms available with {type}',
        'maxlen' => 255,
        'section' => 'step1',
        'label' => 'Connecting room detail modal banner',
        'placeholders' => ['{type}'],
    ],
    [
        'column' => 'portal_ui_step1_per_night_suffix',
        'default' => '/ night',
        'maxlen' => 40,
        'section' => 'step1',
        'label' => 'Room card price per-night suffix',
    ],
    [
        'column' => 'portal_ui_step1_select_button',
        'default' => 'Select',
        'maxlen' => 40,
        'section' => 'step1',
        'label' => 'Select room button',
    ],
    [
        'column' => 'portal_ui_step1_not_available_button',
        'default' => 'Not available',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Not available button',
    ],
    [
        'column' => 'portal_ui_step1_hotel_details_link',
        'default' => 'Hotel details',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Sidebar hotel details link',
    ],
    [
        'column' => 'portal_ui_step1_occupancy_modal_title',
        'default' => 'Rooms and guests',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Occupancy modal title',
    ],
    [
        'column' => 'portal_ui_step1_occupancy_rooms_label',
        'default' => 'Rooms',
        'maxlen' => 40,
        'section' => 'step1',
        'label' => 'Occupancy — rooms',
    ],
    [
        'column' => 'portal_ui_step1_occupancy_adults_label',
        'default' => 'Adults',
        'maxlen' => 40,
        'section' => 'step1',
        'label' => 'Occupancy — adults',
    ],
    [
        'column' => 'portal_ui_step1_occupancy_children_label',
        'default' => 'Children',
        'maxlen' => 40,
        'section' => 'step1',
        'label' => 'Occupancy — children',
    ],
    [
        'column' => 'portal_ui_step1_occupancy_babies_label',
        'default' => 'Babies',
        'maxlen' => 40,
        'section' => 'step1',
        'label' => 'Occupancy — babies',
    ],
    [
        'column' => 'portal_ui_step1_occupancy_modal_note',
        'default' => 'Prices update for extra adults (beyond 2 per room), children, and number of rooms.',
        'maxlen' => 500,
        'section' => 'step1',
        'label' => 'Occupancy modal pricing note',
    ],
    [
        'column' => 'portal_ui_step1_apply_button',
        'default' => 'Apply',
        'maxlen' => 40,
        'section' => 'step1',
        'label' => 'Occupancy modal apply button',
    ],
    [
        'column' => 'portal_ui_step1_filters_modal_title',
        'default' => 'Room filters',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Filters modal title',
    ],
    [
        'column' => 'portal_ui_step1_apply_filters_button',
        'default' => 'Apply filters',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Filters modal apply button',
    ],
    [
        'column' => 'portal_ui_step1_clear_filters_button',
        'default' => 'Clear',
        'maxlen' => 40,
        'section' => 'step1',
        'label' => 'Filters modal clear button',
    ],
    [
        'column' => 'portal_ui_step1_standard_rate_label',
        'default' => 'Standard rate',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Internal rates — standard rate radio',
    ],
    [
        'column' => 'portal_ui_step1_internal_rate_price_zero_suffix',
        'default' => ' — price 0',
        'maxlen' => 40,
        'section' => 'step1',
        'label' => 'Internal rate option price suffix',
    ],
    [
        'column' => 'portal_ui_step1_rate_program_use_points',
        'default' => 'Use Points',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Special rate — use points',
    ],
    [
        'column' => 'portal_ui_step1_rate_program_travel_agents',
        'default' => 'Travel agents',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Special rate — travel agents',
    ],
    [
        'column' => 'portal_ui_step1_rate_program_aaa',
        'default' => 'AAA rate',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Special rate — AAA',
    ],
    [
        'column' => 'portal_ui_step1_rate_program_senior',
        'default' => 'Senior rate',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Special rate — senior',
    ],
    [
        'column' => 'portal_ui_step1_rate_program_government',
        'default' => 'Government and military rates',
        'maxlen' => 255,
        'section' => 'step1',
        'label' => 'Special rate — government/military',
    ],
    [
        'column' => 'portal_ui_step1_code_rate_promo',
        'default' => 'Promotion code',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Code rate — promotion',
    ],
    [
        'column' => 'portal_ui_step1_code_rate_group',
        'default' => 'Group code',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Code rate — group',
    ],
    [
        'column' => 'portal_ui_step1_code_rate_corporate',
        'default' => 'Corporate account',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Code rate — corporate',
    ],
    [
        'column' => 'portal_ui_step1_code_rate_member',
        'default' => 'Member account',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Code rate — member',
    ],
    [
        'column' => 'portal_ui_step1_internal_rate_use_label',
        'default' => 'HOUSE USE (USE)',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Internal rate — house use',
    ],
    [
        'column' => 'portal_ui_step1_internal_rate_comp_label',
        'default' => 'COMPLIMENTARY (COMP)',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Internal rate — complimentary',
    ],
    [
        'column' => 'portal_ui_step1_view_room_details',
        'default' => 'View room details',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'View room details link',
    ],
    [
        'column' => 'portal_ui_step1_direct_book_banner',
        'default' => 'Book direct for the best available rate and flexible stay options.',
        'maxlen' => 500,
        'section' => 'step1',
        'label' => 'Direct booking banner',
    ],
    [
        'column' => 'portal_ui_step1_accessible_room_banner',
        'default' => 'Accessible rooms are available at this property. Use Room Filters and select Accessible room to narrow results.',
        'maxlen' => 500,
        'section' => 'step1',
        'label' => 'Accessible room banner',
    ],
    [
        'column' => 'portal_ui_step1_policy_adults_only',
        'default' => 'Adults only',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room policy badge — adults only',
    ],
    [
        'column' => 'portal_ui_step1_policy_smoking',
        'default' => 'Smoking allowed',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room policy badge — smoking',
    ],
    [
        'column' => 'portal_ui_step1_policy_accessible',
        'default' => 'Accessible',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room policy badge — accessible',
    ],
    [
        'column' => 'portal_ui_step1_policy_crib',
        'default' => 'Crib included',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room policy badge — crib',
    ],
    [
        'column' => 'portal_ui_step1_policy_extra_bed',
        'default' => 'Extra bed available',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room policy badge — extra bed',
    ],
    [
        'column' => 'portal_ui_step1_highlight_guests',
        'default' => 'Guests',
        'maxlen' => 40,
        'section' => 'step1',
        'label' => 'Room highlights — guests column',
    ],
    [
        'column' => 'portal_ui_step1_highlight_room_layout',
        'default' => 'Room layout',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room highlights — layout column',
    ],
    [
        'column' => 'portal_ui_step1_highlight_bathroom',
        'default' => 'Bathroom',
        'maxlen' => 40,
        'section' => 'step1',
        'label' => 'Room highlights — bathroom column',
    ],
    [
        'column' => 'portal_ui_step1_highlight_kitchen',
        'default' => 'Kitchen and dining',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room highlights — kitchen column',
    ],
    [
        'column' => 'portal_ui_step1_hotel_amenities_heading',
        'default' => 'Hotel amenities',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room detail — hotel amenities heading',
    ],
    [
        'column' => 'portal_ui_step1_room_highlights_heading',
        'default' => 'Room highlights',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room detail — highlights heading',
    ],
    [
        'column' => 'portal_ui_step1_more_room_details',
        'default' => 'More room details',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room detail — more details summary',
    ],
    [
        'column' => 'portal_ui_step1_for_your_comfort',
        'default' => 'For your comfort',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room detail — comfort list heading',
    ],
    [
        'column' => 'portal_ui_step1_book_from_prefix',
        'default' => 'Book From',
        'maxlen' => 40,
        'section' => 'step1',
        'label' => 'Room detail book CTA prefix',
    ],
    [
        'column' => 'portal_ui_step1_book_room_title',
        'default' => 'Book this room',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room detail book CTA tooltip',
    ],
    [
        'column' => 'portal_ui_step1_room_desc_lead_default',
        'default' => 'Experience modern luxury in this room with thoughtful design and convenient features. Boasting smart amenities for business and leisure stays.',
        'maxlen' => 'text',
        'section' => 'step1',
        'label' => 'Room marketing copy — description lead',
    ],
    [
        'column' => 'portal_ui_step1_room_desc_extra_default',
        'default' => 'Enjoy quality coffee from the Nespresso coffee machine or a drink from the minibar. The marble bathroom contains a separate bathtub with luxury bath products, cotton bathrobes and slippers.',
        'maxlen' => 'text',
        'section' => 'step1',
        'label' => 'Room marketing copy — description extra',
    ],
    [
        'column' => 'portal_ui_step1_room_spec_default',
        'default' => '38 sq. m., balcony, 55-inch HDTV, minibar, rain shower, WiFi',
        'maxlen' => 500,
        'section' => 'step1',
        'label' => 'Room marketing copy — spec line default',
    ],
    [
        'column' => 'portal_ui_step1_room_types_shown',
        'default' => '{count} room types shown.',
        'maxlen' => 255,
        'section' => 'step1',
        'label' => 'Filtered room count (JS)',
        'placeholders' => ['{count}'],
    ],
    [
        'column' => 'portal_ui_step1_amenity_pool_fallback',
        'default' => 'Outdoor pool',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Amenity fallback — pool (select room)',
    ],

    // --- step2 ---
    [
        'column' => 'portal_ui_step2_select_rate_error',
        'default' => 'Please select a rate.',
        'maxlen' => 255,
        'section' => 'step2',
        'label' => 'Select rate validation error',
    ],
    [
        'column' => 'portal_ui_step2_breakfast_disclaimer_template',
        'default' => "Rates including breakfast reflect adults only. Children's breakfast is charged directly at the Hotel. Children aged {child_min_age} up to and including {child_max_age} years old pay a supplement of {supplement} per day per child should they wish to have breakfast.",
        'maxlen' => 'text',
        'section' => 'step2',
        'label' => 'Breakfast children disclaimer',
        'placeholders' => ['{child_min_age}', '{child_max_age}', '{supplement}'],
    ],
    [
        'column' => 'portal_ui_step2_tourist_tax_note',
        'default' => 'All prices shown include tourist tax for your guest count',
        'maxlen' => 500,
        'section' => 'step2',
        'label' => 'Tourist tax inclusion note',
    ],
    [
        'column' => 'portal_ui_step2_tourist_tax_note_multi_room',
        'default' => ' for this room',
        'maxlen' => 80,
        'section' => 'step2',
        'label' => 'Tourist tax note multi-room suffix',
    ],
    [
        'column' => 'portal_ui_step2_no_rate_plans',
        'default' => 'No rate plans are configured for this hotel.',
        'maxlen' => 255,
        'section' => 'step2',
        'label' => 'No rate plans empty state',
    ],
    [
        'column' => 'portal_ui_step2_breakfast_not_included',
        'default' => 'Breakfast not included.',
        'maxlen' => 255,
        'section' => 'step2',
        'label' => 'Rate card — breakfast not included',
    ],
    [
        'column' => 'portal_ui_step2_breakfast_addon_template',
        'default' => 'Breakfast add-on: {adult_price} per adult, {child_price} per child per night (babies {baby_price}).',
        'maxlen' => 500,
        'section' => 'step2',
        'label' => 'Rate card — breakfast add-on line',
        'placeholders' => ['{adult_price}', '{child_price}', '{baby_price}'],
    ],
    [
        'column' => 'portal_ui_shared_per_night',
        'default' => '/ night',
        'maxlen' => 40,
        'section' => 'step2',
        'label' => 'Per-night suffix (shared step2/step3)',
    ],
    [
        'column' => 'portal_ui_step2_stay_total_label',
        'default' => 'stay total',
        'maxlen' => 40,
        'section' => 'step2',
        'label' => 'Rate card stay total label',
    ],
    [
        'column' => 'portal_ui_step2_select_button',
        'default' => 'Select',
        'maxlen' => 40,
        'section' => 'step2',
        'label' => 'Select rate button',
    ],
    [
        'column' => 'portal_ui_step2_your_rooms_heading',
        'default' => 'Your rooms ({current} of {total})',
        'maxlen' => 80,
        'section' => 'step2',
        'label' => 'Multi-room summary heading',
        'placeholders' => ['{current}', '{total}'],
    ],
    [
        'column' => 'portal_ui_step2_pay_badge_pay_at_hotel',
        'default' => 'Pay when you stay',
        'maxlen' => 80,
        'section' => 'step2',
        'label' => 'Rate pay badge — pay at hotel',
    ],
    [
        'column' => 'portal_ui_step2_pay_badge_non_refundable',
        'default' => 'Non-refundable',
        'maxlen' => 80,
        'section' => 'step2',
        'label' => 'Rate pay badge — non-refundable',
    ],
    [
        'column' => 'portal_ui_step2_back_button',
        'default' => 'Back',
        'maxlen' => 40,
        'section' => 'step2',
        'label' => 'Back to room selection',
    ],

    // --- step3 ---
    [
        'column' => 'portal_ui_step3_pep_error',
        'default' => 'Please confirm you have read the Personal Emergency Plan (PEP) before continuing.',
        'maxlen' => 500,
        'section' => 'step3',
        'label' => 'Accessibility PEP validation error',
    ],
    [
        'column' => 'portal_ui_step3_upgrade_heading',
        'default' => 'We found a better room for you!',
        'maxlen' => 255,
        'section' => 'step3',
        'label' => 'Room upgrade heading',
    ],
    [
        'column' => 'portal_ui_step3_upgrade_pitch_default',
        'default' => 'You deserve a little extra. Enjoy a room with added perks.',
        'maxlen' => 500,
        'section' => 'step3',
        'label' => 'Room upgrade pitch fallback',
    ],
    [
        'column' => 'portal_ui_shared_per_night_meta',
        'default' => 'per night',
        'maxlen' => 40,
        'section' => 'step3',
        'label' => 'Per-night meta label (upgrade card)',
    ],
    [
        'column' => 'portal_ui_step3_special_requests_heading',
        'default' => 'Special requests',
        'maxlen' => 80,
        'section' => 'step3',
        'label' => 'Special requests section heading',
    ],
    [
        'column' => 'portal_ui_step3_no_special_requests',
        'default' => 'No special requests available.',
        'maxlen' => 255,
        'section' => 'step3',
        'label' => 'No special requests hint',
    ],
    [
        'column' => 'portal_ui_step3_traveling_with_pet',
        'default' => 'Traveling with a pet',
        'maxlen' => 80,
        'section' => 'step3',
        'label' => 'Pet checkbox label',
    ],
    [
        'column' => 'portal_ui_step3_pet_policy_template',
        'default' => 'Pets allowed, {non_refundable_fee} non-refundable fee, {max_weight} kg maximum, daily fee {daily_fee} per night',
        'maxlen' => 500,
        'section' => 'step3',
        'label' => 'Pet policy hint',
        'placeholders' => ['{non_refundable_fee}', '{max_weight}', '{daily_fee}'],
    ],
    [
        'column' => 'portal_ui_step3_service_animal',
        'default' => 'Traveling with a service animal',
        'maxlen' => 80,
        'section' => 'step3',
        'label' => 'Service animal checkbox label',
    ],
    [
        'column' => 'portal_ui_step3_accessibility_heading',
        'default' => 'Accessibility',
        'maxlen' => 80,
        'section' => 'step3',
        'label' => 'Accessibility section heading',
    ],
    [
        'column' => 'portal_ui_step3_accessibility_need_prompt',
        'default' => 'Do you have any accessibility needs?',
        'maxlen' => 255,
        'section' => 'step3',
        'label' => 'Accessibility needs field label',
    ],
    [
        'column' => 'portal_ui_step3_pep_intro',
        'default' => 'A Personal Emergency Plan (PEP) applies when accessibility needs are selected.',
        'maxlen' => 500,
        'section' => 'step3',
        'label' => 'PEP introduction sentence',
    ],
    [
        'column' => 'portal_ui_step3_pep_document_link',
        'default' => 'Read the PEP document ↗',
        'maxlen' => 80,
        'section' => 'step3',
        'label' => 'PEP document link text',
    ],
    [
        'column' => 'portal_ui_step3_pep_ack_checkbox',
        'default' => 'I have read the Personal Emergency Plan (PEP)',
        'maxlen' => 255,
        'section' => 'step3',
        'label' => 'PEP acknowledgement checkbox',
    ],
    [
        'column' => 'portal_ui_step3_comments_placeholder',
        'default' => 'Optional requests (130 characters max)',
        'maxlen' => 255,
        'section' => 'step3',
        'label' => 'Additional comments placeholder',
    ],
    [
        'column' => 'portal_ui_shared_guarantee_disclaimer',
        'default' => 'The hotel cannot guarantee additional requests.',
        'maxlen' => 500,
        'section' => 'step3',
        'label' => 'Additional requests disclaimer (shared step3/confirm)',
    ],
    [
        'column' => 'portal_ui_step3_continue_button',
        'default' => 'Continue',
        'maxlen' => 40,
        'section' => 'step3',
        'label' => 'Continue to guest details button',
    ],
    [
        'column' => 'portal_ui_step3_continue_title',
        'default' => 'Continue to guest details',
        'maxlen' => 80,
        'section' => 'step3',
        'label' => 'Continue button tooltip',
    ],
    [
        'column' => 'portal_ui_step3_accessibility_none',
        'default' => 'None',
        'maxlen' => 80,
        'section' => 'step3',
        'label' => 'Accessibility need — none',
    ],
    [
        'column' => 'portal_ui_step3_accessibility_mobility',
        'default' => 'Mobility impairments (wheelchair users, walkers)',
        'maxlen' => 255,
        'section' => 'step3',
        'label' => 'Accessibility need — mobility',
    ],
    [
        'column' => 'portal_ui_step3_accessibility_hearing',
        'default' => 'Hearing impairments (visual alarms, flashing alerts)',
        'maxlen' => 255,
        'section' => 'step3',
        'label' => 'Accessibility need — hearing',
    ],
    [
        'column' => 'portal_ui_step3_accessibility_visual',
        'default' => 'Visual impairments (tactile signage, high-contrast design)',
        'maxlen' => 255,
        'section' => 'step3',
        'label' => 'Accessibility need — visual',
    ],
    [
        'column' => 'portal_ui_step3_accessibility_cognitive',
        'default' => 'Cognitive impairments (clear layouts, simple controls)',
        'maxlen' => 255,
        'section' => 'step3',
        'label' => 'Accessibility need — cognitive',
    ],
    [
        'column' => 'portal_ui_step3_accessibility_other',
        'default' => 'Other',
        'maxlen' => 80,
        'section' => 'step3',
        'label' => 'Accessibility need — other',
    ],
    [
        'column' => 'portal_ui_step3_additional_comments_heading',
        'default' => 'Additional comments',
        'maxlen' => 80,
        'section' => 'step3',
        'label' => 'Additional comments section heading',
    ],

    // --- step4 ---
    [
        'column' => 'portal_ui_step4_session_expired',
        'default' => 'Checkout session expired. Please start your reservation again.',
        'maxlen' => 500,
        'section' => 'step4',
        'label' => 'Checkout session expired error',
    ],
    [
        'column' => 'portal_ui_step4_name_email_required',
        'default' => 'Name and email are required.',
        'maxlen' => 255,
        'section' => 'step4',
        'label' => 'Name/email required error',
    ],
    [
        'column' => 'portal_ui_step4_invalid_email',
        'default' => 'Please enter a valid email address.',
        'maxlen' => 255,
        'section' => 'step4',
        'label' => 'Invalid email error',
    ],
    [
        'column' => 'portal_ui_step4_invalid_phone',
        'default' => 'Please enter a valid phone number with country code (e.g. {phone_example}).',
        'maxlen' => 500,
        'section' => 'step4',
        'label' => 'Invalid phone error',
        'placeholders' => ['{phone_example}'],
    ],
    [
        'column' => 'portal_ui_step4_invalid_dates',
        'default' => 'Invalid dates.',
        'maxlen' => 255,
        'section' => 'step4',
        'label' => 'Invalid dates error',
    ],
    [
        'column' => 'portal_ui_step4_pricing_error',
        'default' => 'Unable to price this stay. Please start again.',
        'maxlen' => 500,
        'section' => 'step4',
        'label' => 'Pricing failure error',
    ],
    [
        'column' => 'portal_ui_step4_save_guest_error',
        'default' => 'Could not save guest details.',
        'maxlen' => 255,
        'section' => 'step4',
        'label' => 'Save guest details error',
    ],
    [
        'column' => 'portal_ui_step4_booking_failed',
        'default' => 'Booking failed.',
        'maxlen' => 255,
        'section' => 'step4',
        'label' => 'Booking insert failure',
    ],
    [
        'column' => 'portal_ui_step4_total_due_label',
        'default' => 'Total due:',
        'maxlen' => 40,
        'section' => 'step4',
        'label' => 'Total due label',
    ],
    [
        'column' => 'portal_ui_step4_full_name_label',
        'default' => 'Full name',
        'maxlen' => 40,
        'section' => 'step4',
        'label' => 'Guest form — full name',
    ],
    [
        'column' => 'portal_ui_step4_email_label',
        'default' => 'Email',
        'maxlen' => 40,
        'section' => 'step4',
        'label' => 'Guest form — email',
    ],
    [
        'column' => 'portal_ui_step4_phone_label',
        'default' => 'Phone',
        'maxlen' => 40,
        'section' => 'step4',
        'label' => 'Guest form — phone',
    ],
    [
        'column' => 'portal_ui_step4_phone_hint',
        'default' => 'Full number with country code (e.g. {phone_example}).',
        'maxlen' => 255,
        'section' => 'step4',
        'label' => 'Phone field hint',
        'placeholders' => ['{phone_example}'],
    ],
    [
        'column' => 'portal_ui_step4_payment_label',
        'default' => 'Payment',
        'maxlen' => 40,
        'section' => 'step4',
        'label' => 'Payment method group label',
    ],
    [
        'column' => 'portal_ui_step4_pay_stripe',
        'default' => 'Pay now with card (Stripe)',
        'maxlen' => 80,
        'section' => 'step4',
        'label' => 'Pay now with Stripe option',
    ],
    [
        'column' => 'portal_ui_step4_pay_at_hotel',
        'default' => 'Pay at the hotel',
        'maxlen' => 80,
        'section' => 'step4',
        'label' => 'Pay at hotel option',
    ],
    [
        'column' => 'portal_ui_step4_check_in_label',
        'default' => 'Check-in',
        'maxlen' => 40,
        'section' => 'step4',
        'label' => 'Locked check-in label',
    ],
    [
        'column' => 'portal_ui_step4_check_out_label',
        'default' => 'Check-out',
        'maxlen' => 40,
        'section' => 'step4',
        'label' => 'Locked check-out label',
    ],
    [
        'column' => 'portal_ui_step4_agreement_text',
        'default' => 'By completing this booking you agree to the booking conditions, general terms, privacy policy, and Wallet terms.',
        'maxlen' => 'text',
        'section' => 'step4',
        'label' => 'Legal terms block',
    ],
    [
        'column' => 'portal_ui_step4_agree_checkbox',
        'default' => 'I agree to these terms',
        'maxlen' => 255,
        'section' => 'step4',
        'label' => 'Terms agreement checkbox',
    ],
    [
        'column' => 'portal_ui_step4_book_reservation_button',
        'default' => 'Book Reservation',
        'maxlen' => 80,
        'section' => 'step4',
        'label' => 'Book reservation submit button',
    ],
    [
        'column' => 'portal_ui_step4_terms_alert',
        'default' => 'Please agree to the terms and conditions to proceed.',
        'maxlen' => 500,
        'section' => 'step4',
        'label' => 'Terms agreement alert',
    ],
    [
        'column' => 'portal_ui_step4_back_button',
        'default' => 'Back',
        'maxlen' => 40,
        'section' => 'step4',
        'label' => 'Back to customize',
    ],

    // --- confirm (portal_checkout.php) ---
    [
        'column' => 'portal_ui_confirm_reservation_summary_title',
        'default' => 'Reservation summary',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Reservation summary card title',
    ],
    [
        'column' => 'portal_ui_confirm_subject_to_approval',
        'default' => 'Subject to hotel approval',
        'maxlen' => 255,
        'section' => 'confirm',
        'label' => 'Requires-approval banner',
    ],
    [
        'column' => 'portal_ui_confirm_rate_prefix',
        'default' => 'Rate:',
        'maxlen' => 40,
        'section' => 'confirm',
        'label' => 'Rate line prefix',
    ],
    [
        'column' => 'portal_ui_confirm_change_rate_link',
        'default' => 'Change rate',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Change rate link',
    ],
    [
        'column' => 'portal_ui_confirm_complimentary_credit',
        'default' => 'Complimentary room credit',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Complimentary credit line',
    ],
    [
        'column' => 'portal_ui_confirm_total_room_charges',
        'default' => 'Total room charges',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Total room charges line',
    ],
    [
        'column' => 'portal_ui_confirm_traveling_with_pet',
        'default' => 'Traveling with a pet',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Pet fee line label',
    ],
    [
        'column' => 'portal_ui_confirm_total_taxes',
        'default' => 'Total taxes and government charges',
        'maxlen' => 255,
        'section' => 'confirm',
        'label' => 'Taxes total line',
    ],
    [
        'column' => 'portal_ui_confirm_total_for_stay',
        'default' => 'Total for stay:',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Grand total label',
    ],
    [
        'column' => 'portal_ui_confirm_tax_per_person_suffix',
        'default' => ' per person per night',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Tax detail per-person suffix',
    ],
    [
        'column' => 'portal_ui_confirm_room_slot_label',
        'default' => 'Room {room}',
        'maxlen' => 40,
        'section' => 'confirm',
        'label' => 'Multi-room slot prefix',
        'placeholders' => ['{room}'],
    ],
    [
        'column' => 'portal_ui_confirm_your_rooms_heading',
        'default' => 'Your rooms',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Payment confirmation — your rooms dt',
    ],
    [
        'column' => 'portal_ui_confirm_reservation_confirmed_title',
        'default' => 'Reservation confirmed',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Confirmation page title — confirmed',
    ],
    [
        'column' => 'portal_ui_confirm_reservation_cancelled_title',
        'default' => 'Reservation cancelled',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Confirmation page title — cancelled',
    ],
    [
        'column' => 'portal_ui_confirm_lead_confirmed',
        'default' => 'Thank you{name}. Your stay is on file with the hotel.',
        'maxlen' => 500,
        'section' => 'confirm',
        'label' => 'Confirmation lead — confirmed',
        'placeholders' => ['{name}'],
    ],
    [
        'column' => 'portal_ui_confirm_lead_cancelled',
        'default' => 'Your reservation has been cancelled.',
        'maxlen' => 500,
        'section' => 'confirm',
        'label' => 'Confirmation lead — cancelled',
    ],
    [
        'column' => 'portal_ui_confirm_lead_cancelled_named',
        'default' => 'Thank you, {name}. Your reservation has been cancelled.',
        'maxlen' => 500,
        'section' => 'confirm',
        'label' => 'Confirmation lead — cancelled with name',
        'placeholders' => ['{name}'],
    ],
    [
        'column' => 'portal_ui_confirm_confirmation_number',
        'default' => 'Confirmation number',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Confirmation number label',
    ],
    [
        'column' => 'portal_ui_confirm_auth_code',
        'default' => 'Auth code',
        'maxlen' => 40,
        'section' => 'confirm',
        'label' => 'Auth code label',
    ],
    [
        'column' => 'portal_ui_confirm_status_label',
        'default' => 'Status',
        'maxlen' => 40,
        'section' => 'confirm',
        'label' => 'Booking status label',
    ],
    [
        'column' => 'portal_ui_confirm_status_cancelled',
        'default' => 'Cancelled',
        'maxlen' => 40,
        'section' => 'confirm',
        'label' => 'Cancelled status badge',
    ],
    [
        'column' => 'portal_ui_confirm_guests_label',
        'default' => 'Guests',
        'maxlen' => 40,
        'section' => 'confirm',
        'label' => 'Guests detail label',
    ],
    [
        'column' => 'portal_ui_confirm_room_label',
        'default' => 'Room',
        'maxlen' => 40,
        'section' => 'confirm',
        'label' => 'Single room detail label',
    ],
    [
        'column' => 'portal_ui_confirm_rate_label',
        'default' => 'Rate',
        'maxlen' => 40,
        'section' => 'confirm',
        'label' => 'Rate detail label',
    ],
    [
        'column' => 'portal_ui_confirm_number_of_nights',
        'default' => 'Number of nights',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Nights detail label',
    ],
    [
        'column' => 'portal_ui_confirm_total_for_stay_detail',
        'default' => 'Total for stay',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Total for stay detail dt',
    ],
    [
        'column' => 'portal_ui_confirm_payment_received',
        'default' => 'Payment received online.',
        'maxlen' => 255,
        'section' => 'confirm',
        'label' => 'Payment notice — paid online lead',
    ],
    [
        'column' => 'portal_ui_confirm_payment_received_body',
        'default' => 'Stripe Checkout completed for this reservation. Any remaining balance is due according to hotel policy.',
        'maxlen' => 500,
        'section' => 'confirm',
        'label' => 'Payment notice — paid online body',
    ],
    [
        'column' => 'portal_ui_confirm_payment_pending_lead',
        'default' => 'Payment pending.',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Payment notice — pending lead',
    ],
    [
        'column' => 'portal_ui_confirm_payment_pending_body',
        'default' => 'Complete card payment via Stripe or pay at the hotel according to policy.',
        'maxlen' => 500,
        'section' => 'confirm',
        'label' => 'Payment notice — pending body',
    ],
    [
        'column' => 'portal_ui_confirm_payment_options_lead',
        'default' => 'Payment options.',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Payment notice — options lead',
    ],
    [
        'column' => 'portal_ui_confirm_payment_options_body',
        'default' => 'Pay online with Stripe when offered at checkout, or pay at the hotel according to policy.',
        'maxlen' => 500,
        'section' => 'confirm',
        'label' => 'Payment notice — options body',
    ],
    [
        'column' => 'portal_ui_confirm_payment_at_hotel_lead',
        'default' => 'Payment at the hotel.',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Payment notice — hotel only lead',
    ],
    [
        'column' => 'portal_ui_confirm_payment_at_hotel_body',
        'default' => 'Online payment is not enabled for this hotel. No charge was made online — the total above is due according to hotel policy.',
        'maxlen' => 500,
        'section' => 'confirm',
        'label' => 'Payment notice — hotel only body',
    ],
    [
        'column' => 'portal_ui_confirm_manage_hint_template',
        'default' => 'To view or cancel your reservation later, use your last name: {last_name}, confirmation number: {confirmation}, and auth code: {auth_code} on {manage_link}.',
        'maxlen' => 'text',
        'section' => 'confirm',
        'label' => 'Manage booking hint (HTML)',
        'placeholders' => ['{last_name}', '{confirmation}', '{auth_code}', '{manage_link}'],
    ],
    [
        'column' => 'portal_ui_confirm_save_pdf_button',
        'default' => 'Save booking confirmation',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Save PDF button',
    ],
    [
        'column' => 'portal_ui_confirm_return_home',
        'default' => 'Return home',
        'maxlen' => 40,
        'section' => 'confirm',
        'label' => 'Return home link',
    ],
    [
        'column' => 'portal_ui_confirm_cancelled_notice',
        'default' => 'No further action is required. If you have questions about charges or refunds, please contact the hotel using Change booking in the sidebar.',
        'maxlen' => 'text',
        'section' => 'confirm',
        'label' => 'Cancelled reservation notice',
    ],
    [
        'column' => 'portal_ui_confirm_your_reservation_title',
        'default' => 'Your reservation',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Aside summary title',
    ],
    [
        'column' => 'portal_ui_confirm_reservation_notes_heading',
        'default' => 'Reservation notes',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Reservation notes section heading',
    ],
    [
        'column' => 'portal_ui_confirm_guest_comments_label',
        'default' => 'Guest comments:',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Guest comments label',
    ],
    [
        'column' => 'portal_ui_confirm_pet_hint_daily_fee',
        'default' => 'Daily Fee Applies',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Pet hint — daily fee applies',
    ],
    [
        'column' => 'portal_ui_confirm_cancellation_policy_button',
        'default' => 'Cancellation policy',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Cancellation policy button',
    ],
    [
        'column' => 'portal_ui_confirm_cancellation_loading',
        'default' => 'Loading cancellation policy...',
        'maxlen' => 255,
        'section' => 'confirm',
        'label' => 'Cancellation policy modal loading',
    ],
    [
        'column' => 'portal_ui_confirm_cancellation_load_fail',
        'default' => 'Failed to load cancellation policy.',
        'maxlen' => 255,
        'section' => 'confirm',
        'label' => 'Cancellation policy modal error',
    ],
    [
        'column' => 'portal_ui_confirm_change_booking_button',
        'default' => 'Change booking',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Change booking button',
    ],
    [
        'column' => 'portal_ui_confirm_change_booking_modal_note',
        'default' => 'To change your reservation, please contact the hotel.',
        'maxlen' => 500,
        'section' => 'confirm',
        'label' => 'Change booking modal note',
    ],
    [
        'column' => 'portal_ui_confirm_cancel_booking_button',
        'default' => 'Cancel Booking',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Cancel booking button',
    ],
    [
        'column' => 'portal_ui_confirm_cancel_confirm_prompt',
        'default' => 'Cancel this reservation? This cannot be undone.',
        'maxlen' => 500,
        'section' => 'confirm',
        'label' => 'Cancel booking confirm dialog',
    ],
    [
        'column' => 'portal_ui_confirm_cancel_already_cancelled',
        'default' => 'This reservation is cancelled.',
        'maxlen' => 255,
        'section' => 'confirm',
        'label' => 'Already cancelled note',
    ],
    [
        'column' => 'portal_ui_confirm_cancel_not_available',
        'default' => 'Online cancellation is not available for this stay. Please contact the hotel.',
        'maxlen' => 500,
        'section' => 'confirm',
        'label' => 'Online cancel unavailable note',
    ],
    [
        'column' => 'portal_ui_confirm_change_room_link',
        'default' => 'Change Room',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Checkout stepper change room link',
    ],
    [
        'column' => 'portal_ui_confirm_stripe_success',
        'default' => 'Payment received. Your reservation is confirmed.',
        'maxlen' => 500,
        'section' => 'confirm',
        'label' => 'Stripe return — success flash',
    ],
    [
        'column' => 'portal_ui_confirm_stripe_cancel',
        'default' => 'Online payment was cancelled. Your reservation is saved — you can pay at the hotel or try again from {manage_label}.',
        'maxlen' => 500,
        'section' => 'confirm',
        'label' => 'Stripe return — cancel flash',
        'placeholders' => ['{manage_label}'],
    ],
    [
        'column' => 'portal_ui_confirm_stripe_error',
        'default' => 'Online payment could not be started. Please contact the hotel or try again later.',
        'maxlen' => 500,
        'section' => 'confirm',
        'label' => 'Stripe return — error flash',
    ],
    [
        'column' => 'portal_ui_confirm_cancel_success',
        'default' => 'Your reservation has been cancelled.',
        'maxlen' => 500,
        'section' => 'confirm',
        'label' => 'Cancel success message',
    ],

    // --- manage ---
    [
        'column' => 'portal_ui_manage_lookup_intro',
        'default' => 'Enter the last name on the reservation, the 10-character confirmation number from your email, and the 12-character auth code (uppercase, lowercase, numbers, and symbols). We will email you a one-time code to continue.',
        'maxlen' => 'text',
        'section' => 'manage',
        'label' => 'Lookup form introduction',
    ],
    [
        'column' => 'portal_ui_manage_last_name_label',
        'default' => 'Last name',
        'maxlen' => 40,
        'section' => 'manage',
        'label' => 'Lookup — last name',
    ],
    [
        'column' => 'portal_ui_manage_confirmation_label',
        'default' => 'Confirmation number',
        'maxlen' => 80,
        'section' => 'manage',
        'label' => 'Lookup — confirmation number',
    ],
    [
        'column' => 'portal_ui_manage_auth_code_label',
        'default' => 'Auth code',
        'maxlen' => 40,
        'section' => 'manage',
        'label' => 'Lookup — auth code',
    ],
    [
        'column' => 'portal_ui_manage_find_reservation_button',
        'default' => 'Find reservation',
        'maxlen' => 80,
        'section' => 'manage',
        'label' => 'Find reservation submit button',
    ],
    [
        'column' => 'portal_ui_manage_otp_title',
        'default' => 'Verify your email',
        'maxlen' => 80,
        'section' => 'manage',
        'label' => 'OTP screen title',
    ],
    [
        'column' => 'portal_ui_manage_otp_intro',
        'default' => 'If your reservation details are correct, we sent a 6-digit code to the email address on file. Enter it below to view your reservation.',
        'maxlen' => 500,
        'section' => 'manage',
        'label' => 'OTP screen introduction',
    ],
    [
        'column' => 'portal_ui_manage_otp_code_label',
        'default' => 'Verification code',
        'maxlen' => 80,
        'section' => 'manage',
        'label' => 'OTP code field label',
    ],
    [
        'column' => 'portal_ui_manage_otp_placeholder',
        'default' => '6-digit code',
        'maxlen' => 40,
        'section' => 'manage',
        'label' => 'OTP input placeholder',
    ],
    [
        'column' => 'portal_ui_manage_verify_button',
        'default' => 'Verify',
        'maxlen' => 40,
        'section' => 'manage',
        'label' => 'OTP verify button',
    ],
    [
        'column' => 'portal_ui_manage_back_button',
        'default' => 'Back',
        'maxlen' => 40,
        'section' => 'manage',
        'label' => 'Manage flow back button',
    ],
    [
        'column' => 'portal_ui_manage_lookup_failure',
        'default' => 'No reservation found. Check your last name, reservation ID, and auth code.',
        'maxlen' => 500,
        'section' => 'manage',
        'label' => 'Lookup failure message',
    ],
    [
        'column' => 'portal_ui_manage_invalid_otp',
        'default' => 'Invalid verification code.',
        'maxlen' => 255,
        'section' => 'manage',
        'label' => 'OTP verification failure',
    ],
    [
        'column' => 'portal_ui_manage_verification_failure',
        'default' => 'Could not complete verification. Please try again later.',
        'maxlen' => 500,
        'section' => 'manage',
        'label' => 'OTP issue failure (generic)',
    ],
    [
        'column' => 'portal_ui_manage_rate_limit',
        'default' => 'Too many attempts. Please wait and try again.',
        'maxlen' => 500,
        'section' => 'manage',
        'label' => 'Lookup rate limit message',
    ],
    [
        'column' => 'portal_ui_manage_otp_rate_limit',
        'default' => 'Too many verification attempts. Please wait and try again.',
        'maxlen' => 500,
        'section' => 'manage',
        'label' => 'OTP rate limit message',
    ],
    [
        'column' => 'portal_ui_manage_missing_fields',
        'default' => 'Enter your last name, confirmation number, and auth code.',
        'maxlen' => 500,
        'section' => 'manage',
        'label' => 'Lookup missing fields error',
    ],
    [
        'column' => 'portal_ui_manage_cancel_requires_otp',
        'default' => 'Email verification is required before cancelling. Please find your reservation again.',
        'maxlen' => 500,
        'section' => 'manage',
        'label' => 'Cancel without OTP error',
    ],
    [
        'column' => 'portal_ui_manage_cancel_failed',
        'default' => 'Unable to cancel this reservation.',
        'maxlen' => 500,
        'section' => 'manage',
        'label' => 'Cancel failure message',
    ],
    [
        'column' => 'portal_ui_manage_reload_after_cancel_failed',
        'default' => 'Reservation cancelled, but the confirmation could not be reloaded.',
        'maxlen' => 500,
        'section' => 'manage',
        'label' => 'Cancel succeeded but reload failed',
    ],
    [
        'column' => 'portal_ui_chrome_your_room_label',
        'default' => 'Your room',
        'maxlen' => 80,
        'section' => 'chrome',
        'label' => 'Stepper — your room label',
    ],
    [
        'column' => 'portal_ui_chrome_reservation_room_title_template',
        'default' => '{bed} {type} Room',
        'maxlen' => 120,
        'section' => 'chrome',
        'label' => 'Reservation room title template',
        'placeholders' => ['{bed}', '{type}'],
    ],
    [
        'column' => 'portal_ui_shared_modal_close',
        'default' => 'Close',
        'maxlen' => 40,
        'section' => 'chrome',
        'label' => 'Modal close button title',
    ],
    [
        'column' => 'portal_ui_shared_opens_in_new_tab',
        'default' => ' (opens in new tab)',
        'maxlen' => 80,
        'section' => 'chrome',
        'label' => 'Link title suffix — opens in new tab',
    ],
    [
        'column' => 'portal_ui_shared_gallery_prev',
        'default' => 'Previous image',
        'maxlen' => 80,
        'section' => 'chrome',
        'label' => 'Gallery previous control',
    ],
    [
        'column' => 'portal_ui_shared_gallery_next',
        'default' => 'Next image',
        'maxlen' => 80,
        'section' => 'chrome',
        'label' => 'Gallery next control',
    ],
    [
        'column' => 'portal_ui_shared_gallery_aria',
        'default' => 'Photo gallery',
        'maxlen' => 80,
        'section' => 'chrome',
        'label' => 'Gallery aria label',
    ],
    [
        'column' => 'portal_ui_home_dates_prev_month',
        'default' => 'Previous month',
        'maxlen' => 80,
        'section' => 'home',
        'label' => 'Dates modal — previous month',
    ],
    [
        'column' => 'portal_ui_home_dates_next_month',
        'default' => 'Next month',
        'maxlen' => 80,
        'section' => 'home',
        'label' => 'Dates modal — next month',
    ],
    [
        'column' => 'portal_ui_home_dates_choose_room',
        'default' => 'Choose Room',
        'maxlen' => 80,
        'section' => 'home',
        'label' => 'Dates modal — choose room button',
    ],
    [
        'column' => 'portal_ui_home_dates_cancel',
        'default' => 'Cancel',
        'maxlen' => 40,
        'section' => 'home',
        'label' => 'Dates modal — cancel button title',
    ],
    [
        'column' => 'portal_ui_home_dates_loading',
        'default' => 'Loading…',
        'maxlen' => 80,
        'section' => 'home',
        'label' => 'Dates modal — calendar loading',
    ],
    [
        'column' => 'portal_ui_home_dates_load_error',
        'default' => 'Could not load calendar.',
        'maxlen' => 255,
        'section' => 'home',
        'label' => 'Dates modal — calendar load error',
    ],
    [
        'column' => 'portal_ui_home_dates_hint_checkin',
        'default' => 'Select your check-in date.',
        'maxlen' => 255,
        'section' => 'home',
        'label' => 'Dates modal — check-in hint',
    ],
    [
        'column' => 'portal_ui_home_dates_hint_checkout',
        'default' => 'Select your check-out date (use ▶ or the month tabs for the next month), or choose room for 1 night.',
        'maxlen' => 'text',
        'section' => 'home',
        'label' => 'Dates modal — check-out hint',
    ],
    [
        'column' => 'portal_ui_home_dates_hint_unavailable',
        'default' => 'Some nights in this range are unavailable. Choose different dates.',
        'maxlen' => 500,
        'section' => 'home',
        'label' => 'Dates modal — unavailable range hint',
    ],
    [
        'column' => 'portal_ui_home_dates_explore_filters',
        'default' => 'Explore all filters and search options >',
        'maxlen' => 255,
        'section' => 'home',
        'label' => 'Dates modal — explore filters link',
    ],
    [
        'column' => 'portal_ui_home_dates_summary_template',
        'default' => 'avg/night for {nights} {night_word} ({tax_label})',
        'maxlen' => 255,
        'section' => 'home',
        'label' => 'Dates modal — summary line template',
        'placeholders' => ['{nights}', '{night_word}', '{tax_label}'],
    ],
    [
        'column' => 'portal_ui_home_dates_weekday_sun',
        'default' => 'Sun',
        'maxlen' => 20,
        'section' => 'home',
        'label' => 'Dates modal — weekday Sun',
    ],
    [
        'column' => 'portal_ui_home_dates_weekday_mon',
        'default' => 'Mon',
        'maxlen' => 20,
        'section' => 'home',
        'label' => 'Dates modal — weekday Mon',
    ],
    [
        'column' => 'portal_ui_home_dates_weekday_tue',
        'default' => 'Tue',
        'maxlen' => 20,
        'section' => 'home',
        'label' => 'Dates modal — weekday Tue',
    ],
    [
        'column' => 'portal_ui_home_dates_weekday_wed',
        'default' => 'Wed',
        'maxlen' => 20,
        'section' => 'home',
        'label' => 'Dates modal — weekday Wed',
    ],
    [
        'column' => 'portal_ui_home_dates_weekday_thu',
        'default' => 'Thu',
        'maxlen' => 20,
        'section' => 'home',
        'label' => 'Dates modal — weekday Thu',
    ],
    [
        'column' => 'portal_ui_home_dates_weekday_fri',
        'default' => 'Fri',
        'maxlen' => 20,
        'section' => 'home',
        'label' => 'Dates modal — weekday Fri',
    ],
    [
        'column' => 'portal_ui_home_dates_weekday_sat',
        'default' => 'Sat',
        'maxlen' => 20,
        'section' => 'home',
        'label' => 'Dates modal — weekday Sat',
    ],
    [
        'column' => 'portal_ui_home_address_new_tab_title',
        'default' => 'Open address in new tab',
        'maxlen' => 120,
        'section' => 'home',
        'label' => 'Hotel address link title',
    ],
    [
        'column' => 'portal_ui_home_general_info_email_title',
        'default' => 'General information email',
        'maxlen' => 120,
        'section' => 'home',
        'label' => 'General info email link title',
    ],
    [
        'column' => 'portal_ui_home_reservations_email_title',
        'default' => 'Reservations email',
        'maxlen' => 120,
        'section' => 'home',
        'label' => 'Reservations email link title',
    ],
    [
        'column' => 'portal_ui_home_call_hotel_title',
        'default' => 'Call hotel',
        'maxlen' => 80,
        'section' => 'home',
        'label' => 'Call hotel link title',
    ],
    [
        'column' => 'portal_ui_step1_rate_programs_legend',
        'default' => 'Rate programs',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Special rates modal — programs legend',
    ],
    [
        'column' => 'portal_ui_step1_apply_special_rates_button',
        'default' => 'Apply',
        'maxlen' => 40,
        'section' => 'step1',
        'label' => 'Special rates modal — apply button',
    ],
    [
        'column' => 'portal_ui_step1_apply_special_rates_title',
        'default' => 'Apply special rates',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Special rates modal — apply button title',
    ],
    [
        'column' => 'portal_ui_step1_room_size_suffix',
        'default' => ' m²',
        'maxlen' => 40,
        'section' => 'step1',
        'label' => 'Room detail — size suffix',
    ],
    [
        'column' => 'portal_ui_step1_room_view_suffix',
        'default' => ' view',
        'maxlen' => 40,
        'section' => 'step1',
        'label' => 'Room detail — view suffix',
    ],
    [
        'column' => 'portal_ui_step1_room_max_occupancy_prefix',
        'default' => 'Max. occupancy:',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room detail — max occupancy prefix',
    ],
    [
        'column' => 'portal_ui_step1_room_adult_singular',
        'default' => 'adult',
        'maxlen' => 40,
        'section' => 'step1',
        'label' => 'Room detail — adult singular',
    ],
    [
        'column' => 'portal_ui_step1_room_adult_plural',
        'default' => 'adults',
        'maxlen' => 40,
        'section' => 'step1',
        'label' => 'Room detail — adult plural',
    ],
    [
        'column' => 'portal_ui_step1_room_child_singular',
        'default' => 'child',
        'maxlen' => 40,
        'section' => 'step1',
        'label' => 'Room detail — child singular',
    ],
    [
        'column' => 'portal_ui_step1_room_child_plural',
        'default' => 'children',
        'maxlen' => 40,
        'section' => 'step1',
        'label' => 'Room detail — child plural',
    ],
    [
        'column' => 'portal_ui_step1_room_children_age_suffix',
        'default' => ' (up to {age} years)',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room detail — children age suffix',
        'placeholders' => ['{age}'],
    ],
    [
        'column' => 'portal_ui_step1_room_baby_singular',
        'default' => 'baby',
        'maxlen' => 40,
        'section' => 'step1',
        'label' => 'Room detail — baby singular',
    ],
    [
        'column' => 'portal_ui_step1_room_baby_plural',
        'default' => 'babies',
        'maxlen' => 40,
        'section' => 'step1',
        'label' => 'Room detail — baby plural',
    ],
    [
        'column' => 'portal_ui_step1_room_sleeps_template',
        'default' => 'Sleeps {count}',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room detail — sleeps highlight',
        'placeholders' => ['{count}'],
    ],
    [
        'column' => 'portal_ui_step1_room_children_welcome_template',
        'default' => 'Children welcome (up to {age} years)',
        'maxlen' => 120,
        'section' => 'step1',
        'label' => 'Room detail — children welcome highlight',
        'placeholders' => ['{age}'],
    ],
    [
        'column' => 'portal_ui_step1_room_babies_welcome',
        'default' => 'Babies welcome',
        'maxlen' => 80,
        'section' => 'step1',
        'label' => 'Room detail — babies welcome highlight',
    ],
    [
        'column' => 'portal_ui_step1_comfort_fallback_list',
        'default' => "Air conditioning\nBath slippers\nBathrobe\nBathroom television\nBidet\nBlack-out curtains\nDuvet covers\nFeather pillows (non-allergenic)\nNon-smoking\nOn-demand movies",
        'maxlen' => 'text',
        'section' => 'step1',
        'label' => 'Room detail — comfort fallback list (one item per line)',
    ],
    [
        'column' => 'portal_ui_step2_multi_room_rated_intro',
        'default' => 'Per-night prices {tax_label} for rooms you already rated. Select a rate for this room below.',
        'maxlen' => 500,
        'section' => 'step2',
        'label' => 'Select rate — multi-room rated intro',
        'placeholders' => ['{tax_label}'],
    ],
    [
        'column' => 'portal_ui_confirm_payment_empty_title',
        'default' => 'No reservation found',
        'maxlen' => 120,
        'section' => 'confirm',
        'label' => 'Payment empty state — title',
    ],
    [
        'column' => 'portal_ui_confirm_payment_empty_lead',
        'default' => 'We could not find a recent booking in this browser session. Start a new search or manage an existing reservation with your confirmation number and last name.',
        'maxlen' => 'text',
        'section' => 'confirm',
        'label' => 'Payment empty state — lead',
    ],
    [
        'column' => 'portal_ui_confirm_payment_empty_cta',
        'default' => 'Find a hotel',
        'maxlen' => 80,
        'section' => 'confirm',
        'label' => 'Payment empty state — CTA',
    ],
    [
        'column' => 'portal_ui_confirm_pdf_not_found_title',
        'default' => 'Confirmation not found',
        'maxlen' => 120,
        'section' => 'confirm',
        'label' => 'PDF gate — document title',
    ],
    [
        'column' => 'portal_ui_confirm_pdf_not_found_body',
        'default' => 'Confirmation is not available. Complete a booking or open this link from your confirmation page in the same browser session.',
        'maxlen' => 'text',
        'section' => 'confirm',
        'label' => 'PDF gate — body message',
    ],
    [
        'column' => 'portal_ui_confirm_pdf_page_title',
        'default' => 'Booking confirmation',
        'maxlen' => 120,
        'section' => 'confirm',
        'label' => 'PDF download page title',
    ],
    [
        'column' => 'portal_ui_auth_sign_in_title',
        'default' => 'Sign in',
        'maxlen' => 80,
        'section' => 'auth',
        'label' => 'Sign in — page title and H1',
    ],
    [
        'column' => 'portal_ui_auth_email_label',
        'default' => 'Email',
        'maxlen' => 80,
        'section' => 'auth',
        'label' => 'Sign in — email label',
    ],
    [
        'column' => 'portal_ui_auth_password_label',
        'default' => 'Password',
        'maxlen' => 80,
        'section' => 'auth',
        'label' => 'Sign in — password label',
    ],
    [
        'column' => 'portal_ui_auth_sign_in_button',
        'default' => 'Sign in',
        'maxlen' => 80,
        'section' => 'auth',
        'label' => 'Sign in — submit button',
    ],
    [
        'column' => 'portal_ui_auth_register_link',
        'default' => 'Register',
        'maxlen' => 80,
        'section' => 'auth',
        'label' => 'Sign in — register link',
    ],
    [
        'column' => 'portal_ui_auth_home_link',
        'default' => 'Home',
        'maxlen' => 80,
        'section' => 'auth',
        'label' => 'Sign in — home link',
    ],
    [
        'column' => 'portal_ui_auth_sign_in_link',
        'default' => 'Sign in',
        'maxlen' => 80,
        'section' => 'auth',
        'label' => 'Register — sign in link',
    ],
    [
        'column' => 'portal_ui_auth_invalid_csrf',
        'default' => 'Invalid CSRF token.',
        'maxlen' => 255,
        'section' => 'auth',
        'label' => 'Auth — invalid CSRF error',
    ],
    [
        'column' => 'portal_ui_auth_invalid_credentials',
        'default' => 'Invalid email or password.',
        'maxlen' => 255,
        'section' => 'auth',
        'label' => 'Sign in — invalid credentials',
    ],
    [
        'column' => 'portal_ui_auth_register_title',
        'default' => 'Register',
        'maxlen' => 80,
        'section' => 'auth',
        'label' => 'Register — page title and H1',
    ],
    [
        'column' => 'portal_ui_auth_full_name_label',
        'default' => 'Full name',
        'maxlen' => 80,
        'section' => 'auth',
        'label' => 'Register — full name label',
    ],
    [
        'column' => 'portal_ui_auth_phone_label',
        'default' => 'Phone',
        'maxlen' => 80,
        'section' => 'auth',
        'label' => 'Register — phone label',
    ],
    [
        'column' => 'portal_ui_auth_all_fields_required',
        'default' => 'All fields required.',
        'maxlen' => 255,
        'section' => 'auth',
        'label' => 'Register — required fields error',
    ],
    [
        'column' => 'portal_ui_auth_register_customer_failed',
        'default' => 'Could not create customer.',
        'maxlen' => 255,
        'section' => 'auth',
        'label' => 'Register — customer create error',
    ],
    [
        'column' => 'portal_ui_auth_email_registered',
        'default' => 'Email may already be registered.',
        'maxlen' => 255,
        'section' => 'auth',
        'label' => 'Register — duplicate email error',
    ],
];
